import { createHash } from 'node:crypto';
import { readFileSync, readdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import * as rules from '../src/index';
import type { GameState } from '../src/schema/game';
import { createSeededGameState } from '../src/tools/seeded-state';

const ROOT = resolve('.');
const OWNER = 'servant.atalanta';
const ID = 'servant.atalanta.skill.sc-atalanta-2';
const SOURCE = 'atalanta-s2-source';
const ABILITY = 'appeal-letter-copy';
const ATTACK_DEF = 'test.atalanta.attack';
const MASTER_ATTACK_DEF = 'test.atalanta.master-attack';
const NON_ATTACK_DEF = 'test.atalanta.non-attack';
const TEXT = '【真名解放】\n唯一/行动阶段：若你拥有地利，创造并激活一张你本回合打出的其他攻击的临时复制。';
const TEXT_SHA = '93fd375fbcb6d5841a26ebf2c1512b48d94e6b6ed963fd0fcafe7d37c58f501b';
const hash = (text: string): string => createHash('sha256').update(text, 'utf8').digest('hex');
function rawArchive(): any { return JSON.parse(readFileSync(resolve(ROOT, 'data/authoring/servants/servant.atalanta.json'), 'utf8').replace(/^\uFEFF/, '')); }
function compiledCard(id: string, cardType = 'servant_attack'): any { return { id, name:id, cardType, cardFace:{typeLabel:'力量',attributes:['力量'],cost:2,basePower:5}, playTiming:{phase:'action',window:'controller_play_card_window'}, playRequirements:[], mode:'automatic', abilities:[] }; }
function setup(mana = 8): GameState {
  const pack:any = rules.loadAuthoringJson(rawArchive()); expect(pack.report).toEqual([]);
  pack.cards[ATTACK_DEF] = compiledCard(ATTACK_DEF); pack.cards[MASTER_ATTACK_DEF] = compiledCard(MASTER_ATTACK_DEF, 'master_deck_card'); pack.cards[NON_ATTACK_DEF] = compiledCard(NON_ATTACK_DEF, 'master_skill');
  const state = createSeededGameState({ activeSeats:[1,2] });
  state.cards=[{instanceId:SOURCE,definitionId:ID,ownerPlayerId:'p1',controllerPlayerId:'p1',zone:'skill',visibility:{scope:'owner_only',ownerPlayerId:'p1'}}];
  state.players[0]!.servantCardId=OWNER; state.players[0]!.mana=mana; state.players[0]!.locationId='miyama_town'; state.players[1]!.locationId='shinto';
  state.round.activePhase='action'; state.round.prioritySeat=state.players[0]!.seat; (state as any).modeState={terrainAssignments:{miyama_town:['p1']}};
  rules.initializeAbilityRuntime(state,pack,{seed:10402}); return state;
}
function play(state:GameState){return rules.dispatchAbilityCommand(state,'p1',{type:'play_card',cardInstanceId:SOURCE});}
function addAttack(state:GameState,id:string,options:{definitionId?:string;owner?:string;controller?:string;zone?:string;playedRound?:number}={}){const owner=options.owner??'p1',controller=options.controller??owner; state.cards.push({instanceId:id,definitionId:options.definitionId??ATTACK_DEF,ownerPlayerId:owner,controllerPlayerId:controller,zone:options.zone??'attack_area',visibility:{scope:'public'}}); state.abilityRuntime!.cardState[id]={active:true,faceDown:false,playedRound:options.playedRound??state.round.roundNumber};}
function activate(state:GameState){return rules.dispatchAbilityCommand(state,'p1',{type:'activate_ability',cardInstanceId:SOURCE,abilityId:ABILITY});}
function choose(state:GameState,selectedIds:string[]){const d=state.abilityRuntime!.pendingDecision!; return rules.dispatchAbilityCommand(state,'p1',{type:'choose_target',decisionId:d.id,selectedIds});}
function authoringJsonFiles(dir:string):string[]{return readdirSync(dir,{withFileTypes:true}).flatMap(entry=>{const full=join(dir,entry.name);return entry.isDirectory()?authoringJsonFiles(full):entry.name.endsWith('.json')?[full]:[];});}

describe('P3 S R104 Atalanta s2 consumer migration',()=>{
  it('authors exactly the frozen identity, accepted source evidence, and locked static metadata',()=>{
    const raw=rawArchive(); expect(raw).toMatchObject({schemaVersion:'fd-card-authoring-v1',archiveType:'servant_skill_card_archive',id:OWNER,name:'阿塔兰忒',class:'Archer',sourcePolicy:{phase3EvidenceCommit:'59f145434695d29bdd17e4cb3adc887e84182377',referenceMetadataCommit:'b2f9fa15fba07c63530bbf4612b03b8b704755f9'}}); expect(raw.cards.map((card:any)=>card.id)).toEqual(['servant.atalanta.skill.sc-atalanta-3', ID]); const card=raw.cards.find((card:any)=>card.id===ID);
    expect(card).toMatchObject({id:ID,aliases:['sc_atalanta_2'],legacyId:'sc_atalanta_2',name:'诉状箭书',cardType:'servant_skill',owner:{type:'servant',id:OWNER},cardFace:{typeLabel:'迅捷/宝具',attributes:['迅捷','宝具'],cost:2,basePower:4},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[{type:'skill_zone_mana_at_least',value:8}],phase3Evidence:{f1Commit:'4c67f72828125bc112b23b738948f5533eaceb8c',f1AuditCommit:'6826dc5b085bf8efa0a53853c0e293e939b0c137',f1ReviewCommit:'826e6f5b6a92b927800b2b50a6b15898d70befcc',f1ClauseSources:[{sourceAbilityId:ABILITY,locator:'skillCards[28].abilities[0].printedClause',sha256:TEXT_SHA}],f1FullPrintedTextSha256:TEXT_SHA,referenceStaticMetadata:{commit:'b2f9fa15fba07c63530bbf4612b03b8b704755f9',legacySkillId:'sc_atalanta_2',class:'Archer',cost:2,basePower:4,legacyRequirement:8,typeLabel:'迅捷/宝具',attributes:['迅捷','宝具']},canonicalSkillZoneManaRequirement:{value:8,authority:'final_rules_9.4'}}});
    expect(card.printedText).toBe(TEXT); expect(card.abilities).toHaveLength(1); expect(card.abilities[0].printedClause).toBe(TEXT); expect(hash(card.printedText)).toBe(TEXT_SHA); expect(hash(card.abilities[0].printedClause)).toBe(TEXT_SHA);
  });
  it('loads blocker-free through exactly the accepted FB2-50 whole-ability envelope',()=>{const pack=rules.loadAuthoringJson(rawArchive()); expect(pack.report).toEqual([]); const ability=pack.cards[ID]!.abilities[0]!; expect(pack.cards[ID]!.mode).toBe('automatic'); expect(rules.isAcceptedSelectedPlayedAttackTemporaryCopyAbility(ability,'compiled')).toBe(true); expect(ability).toMatchObject({id:ABILITY,kind:'phase_action',activation:{phase:'action',opens:'controller_action_window'},conditions:[{type:'source_active'},{type:'gt',left:{var:'controller.deployment_bonus'},right:0}],effects:[{type:rules.SELECTED_PLAYED_ATTACK_TEMPORARY_COPY_EFFECT,target:'selected_attack'}],visibility:{revealsTrueName:true,revealTiming:'on_use_declared',revealScope:'servant_package'},execution:{mode:'automatic'}});});
  it('enforces the 7/8 mana skill-zone boundary and charges printed cost 2',()=>{const low=setup(7),before=structuredClone(low); expect(play(low).ok).toBe(false); expect(low).toEqual(before); const state=setup(8); expect(play(state).ok).toBe(true); expect(state.players[0]!.mana).toBe(6); expect(state.cards[0]!.zone).toBe('attack_area'); expect(state.abilityRuntime!.cardState[SOURCE]).toMatchObject({active:true,faceDown:false,playedRound:state.round.roundNumber}); expect(state.abilityRuntime!.revealedServants).not.toContain('p1');});
  it('requires deployment bonus and offers only other current-round controller attacks',()=>{const state=setup(); expect(play(state).ok).toBe(true); addAttack(state,'eligible'); addAttack(state,'master',{definitionId:MASTER_ATTACK_DEF}); addAttack(state,'old',{playedRound:state.round.roundNumber-1}); addAttack(state,'hand',{zone:'hand'}); addAttack(state,'foreign',{owner:'p2',controller:'p2'}); addAttack(state,'nonattack',{definitionId:NON_ATTACK_DEF}); expect(activate(state).ok).toBe(true); expect(state.abilityRuntime!.revealedServants).toContain('p1'); expect(state.abilityRuntime!.pendingDecision?.candidates).toEqual(['eligible','master']);
    const noTerrain=setup(); expect(play(noTerrain).ok).toBe(true); addAttack(noTerrain,'eligible'); (noTerrain as any).modeState.terrainAssignments.miyama_town=[]; const before=structuredClone(noTerrain); expect(activate(noTerrain).ok).toBe(false); expect(noTerrain).toEqual(before);});
  it('creates exactly one free active face-up temporary same-definition attack without ordinary play semantics',()=>{const state=setup(); expect(play(state).ok).toBe(true); addAttack(state,'chosen'); const mana=state.players[0]!.mana,counters=structuredClone(state.abilityRuntime!.playCounters),events=state.abilityRuntime!.events.filter(e=>e.type==='on_card_played').length; expect(activate(state).ok).toBe(true); const decisionId=state.abilityRuntime!.pendingDecision!.id; expect(choose(state,['chosen']).ok).toBe(true); const copy=state.cards.find(c=>c.generatedBy===SOURCE)!; expect(copy).toMatchObject({definitionId:ATTACK_DEF,ownerPlayerId:'p1',controllerPlayerId:'p1',zone:'attack_area',visibility:{scope:'public'},generatedBy:SOURCE}); expect(state.abilityRuntime!.cardState[copy.instanceId]).toEqual({active:true,faceDown:false,playedRound:0}); expect(state.players[0]!.mana).toBe(mana); expect(state.abilityRuntime!.playCounters).toEqual(counters); expect(state.abilityRuntime!.events.filter(e=>e.type==='on_card_played')).toHaveLength(events); expect(rules.dispatchAbilityCommand(state,'p1',{type:'choose_target',decisionId,selectedIds:['chosen']}).ok).toBe(false); expect(state.cards.filter(c=>c.generatedBy===SOURCE)).toHaveLength(1);});
  it('fails closed on stale or forged target provenance',()=>{for(const corrupt of [(s:GameState)=>{s.abilityRuntime!.cardState['chosen']!.playedRound=s.round.roundNumber-1;},(s:GameState)=>{s.cards.find(c=>c.instanceId==='chosen')!.zone='hand';},(s:GameState)=>{s.cards.find(c=>c.instanceId==='chosen')!.controllerPlayerId='p2';},(s:GameState)=>{s.cards.find(c=>c.instanceId==='chosen')!.definitionId=NON_ATTACK_DEF;}]){const state=setup(); expect(play(state).ok).toBe(true); addAttack(state,'chosen'); expect(activate(state).ok).toBe(true); corrupt(state); const before=structuredClone(state); expect(choose(state,['chosen']).ok).toBe(false); expect(state).toEqual(before);} const forged=setup(); expect(play(forged).ok).toBe(true); addAttack(forged,'chosen'); expect(activate(forged).ok).toBe(true); const before=structuredClone(forged); expect(choose(forged,['outsider']).ok).toBe(false); expect(forged).toEqual(before);});
  it('revalidates source/deployment state at settlement and removes the copy next round',()=>{const source=setup(); expect(play(source).ok).toBe(true); addAttack(source,'chosen'); expect(activate(source).ok).toBe(true); source.abilityRuntime!.cardState[SOURCE]!.active=false; const before=structuredClone(source); expect(choose(source,['chosen']).ok).toBe(false); expect(source).toEqual(before);
    const terrain=setup(); expect(play(terrain).ok).toBe(true); addAttack(terrain,'chosen'); expect(activate(terrain).ok).toBe(true); (terrain as any).modeState.terrainAssignments.miyama_town=[]; const terrainBefore=structuredClone(terrain); expect(choose(terrain,['chosen']).ok).toBe(false); expect(terrain).toEqual(terrainBefore);
    const cleanup=setup(); expect(play(cleanup).ok).toBe(true); addAttack(cleanup,'chosen'); expect(activate(cleanup).ok).toBe(true); expect(choose(cleanup,['chosen']).ok).toBe(true); const copy=cleanup.cards.find(c=>c.generatedBy===SOURCE)!; rules.advanceAbilityPhase(cleanup,'preparation',cleanup.round.roundNumber+1); expect(cleanup.cards.find(c=>c.instanceId===copy.instanceId)?.zone).toBe('removed_from_game'); expect(cleanup.abilityRuntime!.ongoingEffects.some(e=>e.sourceCardId===copy.instanceId)).toBe(false);});
  it('stays outside product/generated outputs and is exactly the sole +1 frozen material addition',()=>{const manifest=readFileSync(resolve(ROOT,'data/packs/fd-playtest-v1/pack.json'),'utf8'); const generated=readFileSync(resolve(ROOT,'data/generated/fd-playtest-v1.content-library.json'),'utf8'); expect(manifest).not.toContain(ID); expect(generated).not.toContain(ID); const inventory=JSON.parse(readFileSync(resolve(ROOT,'data/phase3/full-roster-ability-inventory.json'),'utf8')); const frozen=new Set<string>([...inventory.staticSkills.map((x:any)=>x.canonicalAbilityId),...inventory.dynamicSkills.map((x:any)=>x.canonicalAbilityId)]); const counts=new Map<string,number>(); for(const file of authoringJsonFiles(resolve(ROOT,'data/authoring'))){const archive=JSON.parse(readFileSync(file,'utf8').replace(/^\uFEFF/,'')); for(const card of archive.cards??[]) counts.set(card.id,(counts.get(card.id)??0)+1);} const overlap=[...counts.keys()].filter(id=>frozen.has(id)); const duplicateFrozen=[...counts.entries()].filter(([id,count])=>frozen.has(id)&&count>1); expect(frozen.size).toBe(944); expect(overlap).toHaveLength(148); expect(duplicateFrozen).toEqual([]); expect(counts.get(ID)).toBe(1);});
});
