import { describe, expect, it } from 'vitest';
import * as rules from '../src/index';
import { createSeededGameState } from '../src/tools/seeded-state';
const CARD='servant.fixture.skill.exile-trigger', SOURCE='exile-trigger-source';
function archive(){return {schemaVersion:'fd-card-authoring-v1',archiveType:'servant_skill_card_archive',id:'servant.fixture',name:'fixture',class:'Servant',cards:[{id:CARD,name:'fixture',cardType:'servant_skill',owner:{type:'servant',id:'servant.fixture'},cardFace:{typeLabel:'fixture',attributes:[],cost:0,basePower:0},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[],abilities:[
{id:'arm-and-exile',kind:'phase_action',printedClause:'fixture',markers:['m50_structured_v1'],activation:{phase:'action',opens:'controller_action_window'},conditions:[],targets:[],cost:[],effects:[{type:'add_linked_status',target:{scope:'all_players'},status:'flawed'},{type:'exile_source_card'}],ruleModifiers:[],creates:[],lifecycle:{},responseWindow:{},limit:{},visibility:{},execution:{mode:'automatic',allowedOperations:[]}},
{id:'cleanup',kind:'forced_trigger',printedClause:'fixture cleanup',markers:['m50_structured_v1'],activation:{trigger:'m50_card_exiled'},conditions:[{type:'event_definition_is_self'}],targets:[],cost:[],effects:[{type:'remove_linked_status',target:{scope:'all_players'},status:'flawed'}],ruleModifiers:[],creates:[],lifecycle:{},responseWindow:{},limit:{},visibility:{},execution:{mode:'automatic',allowedOperations:[]}}
]}]};}
describe('P3 F4 M50-02 card-exiled trusted internal trigger',()=>{it('cleans source-linked statuses when the source exiles itself',()=>{const pack=rules.loadAuthoringJson(archive()); expect(pack.report).toEqual([]); const s=createSeededGameState({activeSeats:[1,2]}); s.cards=[{instanceId:SOURCE,definitionId:CARD,ownerPlayerId:'p1',controllerPlayerId:'p1',zone:'attack_area',visibility:{scope:'public'}}]; s.round.activePhase='action'; s.round.prioritySeat=s.players[0]!.seat; rules.initializeAbilityRuntime(s,pack,{seed:7}); (s.abilityRuntime!.cardState as any)[SOURCE]={active:true,faceDown:false}; expect(rules.dispatchAbilityCommand(s,'p1',{type:'activate_ability',cardInstanceId:SOURCE,abilityId:'arm-and-exile'}).ok).toBe(true); expect(s.cards[0]!.zone).toBe('removed_from_game'); expect((s.abilityRuntime as any).playerStatusKeysByPlayer).toEqual({p1:[],p2:[]}); expect(s.abilityRuntime!.processedEvents.some((id)=>id.includes('card-exiled'))).toBe(true);});});
