import { describe, expect, it } from 'vitest';
import * as rules from '../src/index';
import type { GameState } from '../src/schema/game';
import { createSeededGameState } from '../src/tools/seeded-state';

const SOURCE_DEF='servant.fixture.poison-dragon'; const SOURCE='poison-source'; const TERRITORY_DEF='servant.fixture.territory'; const TERRITORY='territory-source';
function archive(): any { return {schemaVersion:'fd-card-authoring-v1',archiveType:'servant_skill_card_archive',id:'servant.fixture',name:'fixture',class:'Assassin',cards:[{id:SOURCE_DEF,name:'fixture',cardType:'servant_skill',owner:{type:'servant',id:'servant.fixture'},cardFace:{typeLabel:'fixture',attributes:[],cost:0,basePower:0},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[],abilities:[{id:'poison-dragon',kind:'phase_action',printedClause:'fixture',markers:['m50_structured_v1'],activation:{phase:'combat',requiresSourceState:'active',opens:'controller_combat_action_window'},conditions:[{type:'at_battlefield'},{type:'source_active'},{type:'owned_active_card_by_definition',definitionId:TERRITORY_DEF},{type:'target_count_at_least',count:1,target:{scope:'same_battlefield_opponents',where:[{type:'deployed_this_round_at_controller_location'}]}}],targets:[],effects:[{type:'defeat_player',target:{scope:'same_battlefield_opponents',where:[{type:'deployed_this_round_at_controller_location'}]}}],cost:[],ruleModifiers:[],creates:[],lifecycle:{},responseWindow:{},limit:{},visibility:{},execution:{mode:'automatic',allowedOperations:[]}}]}]};}
function setup():GameState {const pack=rules.loadAuthoringJson(archive());expect(pack.report).toEqual([]);const s=createSeededGameState({activeSeats:[1,2,3,4]});s.cards=[{instanceId:SOURCE,definitionId:SOURCE_DEF,ownerPlayerId:'p1',controllerPlayerId:'p1',zone:'attack_area',visibility:{scope:'public'}},{instanceId:TERRITORY,definitionId:TERRITORY_DEF,ownerPlayerId:'p1',controllerPlayerId:'p1',zone:'attack_area',visibility:{scope:'public'}}];for(const id of ['p1','p2','p3']) s.players.find(p=>p.id===id)!.locationId='miyama_town';s.players.find(p=>p.id==='p4')!.locationId='shinto';s.round.activePhase='battle';s.round.prioritySeat=s.players.find(p=>p.id==='p1')!.seat;rules.initializeAbilityRuntime(s,pack,{seed:20260924});s.abilityRuntime!.cardState[SOURCE]={active:true,faceDown:false,playedRound:s.round.roundNumber};s.abilityRuntime!.cardState[TERRITORY]={active:true,faceDown:false,playedRound:0};s.log.push({type:'player_deployment_recorded',message:'p2',payload:{playerId:'p2',locationId:'miyama_town',roundNumber:s.round.roundNumber}},{type:'player_deployment_recorded',message:'p3-old',payload:{playerId:'p3',locationId:'miyama_town',roundNumber:s.round.roundNumber-1}},{type:'player_deployment_recorded',message:'p4',payload:{playerId:'p4',locationId:'shinto',roundNumber:s.round.roundNumber}});return s;}
describe('P3 F4 M50-02 authoritative deployment-location opponent defeat',()=>{
 it('stages only same-battlefield opponents whose server deployment record matches this round and location',()=>{const s=setup();const result=rules.dispatchAbilityCommand(s,'p1',{type:'activate_ability',cardInstanceId:SOURCE,abilityId:'poison-dragon'}); expect(result.ok).toBe(true);expect(s.abilityRuntime!.pendingPreBattleDefeats).toEqual([expect.objectContaining({controllerId:'p1',sourceCardId:SOURCE,abilityId:'poison-dragon',battlefieldId:'miyama_town',targetPlayerIds:['p2']})]);});
 it('does not expose the action without the required active owned support definition',()=>{const s=setup();s.abilityRuntime!.cardState[TERRITORY]!.active=false;const result=rules.dispatchAbilityCommand(s,'p1',{type:'activate_ability',cardInstanceId:SOURCE,abilityId:'poison-dragon'});expect(result.ok).toBe(false);expect(result.rejection?.code).toBe('illegal_action');expect(s.abilityRuntime!.pendingPreBattleDefeats).toEqual([]);});
});
