import { describe, expect, it } from 'vitest';
import * as rules from '../src/index';
import { createSeededGameState } from '../src/tools/seeded-state';
const CARD='servant.fixture.skill.linked-status', SOURCE='linked-status-source';
function archive(effect:any,id:string){return {schemaVersion:'fd-card-authoring-v1',archiveType:'servant_skill_card_archive',id:'servant.fixture',name:'fixture',class:'Servant',cards:[{id:CARD,name:'fixture',cardType:'servant_skill',owner:{type:'servant',id:'servant.fixture'},cardFace:{typeLabel:'fixture',attributes:[],cost:0,basePower:0},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[],abilities:[{id,kind:'phase_action',printedClause:'fixture',markers:['m50_structured_v1'],activation:{phase:'action',opens:'controller_action_window'},conditions:[],targets:[],cost:[],effects:[effect],ruleModifiers:[],creates:[],lifecycle:{},responseWindow:{},limit:{},visibility:{},execution:{mode:'automatic',allowedOperations:[]}}]}]};}
function setup(effect:any,id:string){const pack=rules.loadAuthoringJson(archive(effect,id)); expect(pack.report).toEqual([]); const s=createSeededGameState({activeSeats:[1,2]}); s.cards=[{instanceId:SOURCE,definitionId:CARD,ownerPlayerId:'p1',controllerPlayerId:'p1',zone:'skill',visibility:{scope:'owner_only',ownerPlayerId:'p1'}}]; s.round.activePhase='action'; s.round.prioritySeat=s.players[0]!.seat; rules.initializeAbilityRuntime(s,pack,{seed:1}); return s;}
describe('P3 F4 M50-02 Segment B linked statuses',()=>{
 it('adds a source-instance-qualified status',()=>{const s=setup({type:'add_linked_status',target:{scope:'all_players'},status:'flawed'},'add'); expect(rules.dispatchAbilityCommand(s,'p1',{type:'activate_ability',cardInstanceId:SOURCE,abilityId:'add'}).ok).toBe(true); expect((s.abilityRuntime as any).playerStatusKeysByPlayer).toEqual({p1:['flawed:'+SOURCE],p2:['flawed:'+SOURCE]});});
 it('removes only the matching source-qualified status',()=>{const s=setup({type:'remove_linked_status',target:{scope:'all_players'},status:'flawed'},'remove'); (s.abilityRuntime as any).playerStatusKeysByPlayer={p1:['flawed:'+SOURCE,'flawed:other'],p2:['flawed:'+SOURCE]}; expect(rules.dispatchAbilityCommand(s,'p1',{type:'activate_ability',cardInstanceId:SOURCE,abilityId:'remove'}).ok).toBe(true); expect((s.abilityRuntime as any).playerStatusKeysByPlayer).toEqual({p1:['flawed:other'],p2:[]});});
 it('rejects widened linked-status authoring',()=>{const bad=archive({type:'add_linked_status',status:'flawed',extra:true},'bad'); expect(rules.loadAuthoringJson(bad).report).toEqual(expect.arrayContaining([expect.objectContaining({abilityId:'bad',path:'effects[0]',reason:'Structured linked-status effect shape is invalid'})]));});
});
