import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { loadAuthoringJson } from '../../src/ability/loader';
import { createSeededGameState } from '../../src/tools/seeded-state';
import { dispatchAbilityCommand, initializeAbilityRuntime, processAbilityEvent } from '../../src/ability/interpreter';
import { persistentLocationTerrainAdvantage } from '../../src/ability/persistent-location-terrain-capability';
import { effectiveLocationRestrictionBlocksMovement, effectiveLocationRestrictionRequiresFaceDownStandardAttack, isPlayerAtEffectiveLocationKind } from '../../src/ability/effective-location-restriction-capability';
import { movePlayer } from '../../src/core/movement';
import type { GameState } from '../../src/schema/game';

const ROOT='master.araya';
const S1='master.araya.skill.s1', S1A='master.araya.skill.s1a', ASC='master.araya.skill.ascension';
const raw=()=>JSON.parse(readFileSync('data/authoring/masters/master.araya.json','utf8'));
function add(state:GameState,definitionId:string,zone:any='skill',owner='p1',active=false,faceDown=false){const id=`${owner}:${definitionId}:${state.cards.length}`;state.cards.push({instanceId:id,definitionId,ownerPlayerId:owner,controllerPlayerId:owner,zone,visibility:{scope:'owner_only',ownerPlayerId:owner}} as any);state.abilityRuntime!.cardState[id]={active,faceDown,playedRound:state.round.roundNumber};return id;}
function setup(){const loaded=loadAuthoringJson(raw());expect(loaded.report.filter(x=>x.status==='unsupported')).toEqual([]);(loaded.cards as any)['fixture.araya.basic.cost3']={id:'fixture.araya.basic.cost3',name:'basic3',cardType:'basic_attack',ownerId:'servant.fixture',ownerType:'servant',cardFace:{typeLabel:'基础',attributes:[],cost:3,basePower:2},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[],abilities:[],mode:'automatic'};const state=createSeededGameState({activeSeats:[1,2,3]});state.cards=[];initializeAbilityRuntime(state,loaded,{seed:20261001});state.players[0]!.masterCardId=ROOT;state.players[0]!.locationId='shinto';state.players[1]!.locationId='shinto';state.players[2]!.locationId='miyama_town';state.round.activePhase='action';state.round.prioritySeat=state.players[1]!.seat;(state as any).modeState={terrainAssignments:{shinto:['p1','p2']},terrainAssignmentSlots:{shinto:{p1:0,p2:1}}};const s1=add(state,S1);const s1a=add(state,S1A);const asc=add(state,ASC);return {state,s1,s1a,asc,loaded};}
function buildFive(state:GameState){for(let n=1;n<=5;n++)processAbilityEvent(state,{id:`araya-deploy:${n}`,type:'after_player_deployed_to_battlefield',playerId:'p1',locationId:'shinto'} as any);}
function terminal(){return {id:'araya-battle:after_battle_ended',type:'after_battle_ended' as const,battlePhaseResolutionId:'araya-battle',battleParticipantIds:['p1','p2']};}

describe('P3 Araya owner-complete migration',()=>{
  it('loads exactly the three frozen canonical identities as supported definitions',()=>{const loaded=loadAuthoringJson(raw());expect(Object.keys(loaded.cards).sort()).toEqual([ASC,S1,S1A].sort());expect(loaded.report.filter(x=>x.status==='unsupported')).toEqual([]);expect(raw().cards.find((c:any)=>c.id===ASC).initialPlacement).toBe('outside_game');});
  it('drives canonical Triple Boundary to five persistent terrain layers',()=>{const {state}=setup();buildFive(state);expect(persistentLocationTerrainAdvantage(state,'p1','shinto')).toBe(5);});
  it('drives canonical Paradox Spiral virtual workshop and same-location movement restriction',()=>{const {state}=setup();buildFive(state);expect(isPlayerAtEffectiveLocationKind(state,'p1','workshop')).toBe(true);expect(isPlayerAtEffectiveLocationKind(state,'p2','workshop')).toBe(false);expect(effectiveLocationRestrictionBlocksMovement(state,'p2')).toBe(true);expect(effectiveLocationRestrictionRequiresFaceDownStandardAttack(state,'p2')).toBe(true);const moved=movePlayer(state,{playerId:'p2',to:'recon',movementKind:'normal'});expect(moved.moved).toBe(false);expect(moved.reason).toBe('movement_locked');});
  it('disables Paradox Spiral authority immediately when the canonical ascension source leaves skill',()=>{const {state,asc}=setup();buildFive(state);state.cards.find(c=>c.instanceId===asc)!.zone='discard';expect(isPlayerAtEffectiveLocationKind(state,'p1','workshop')).toBe(false);expect(effectiveLocationRestrictionBlocksMovement(state,'p2')).toBe(false);});
  it('recycles canonical Origin Stillness target and gains printed cost x2 rather than paid mana',()=>{const {state}=setup();const basic=add(state,'fixture.araya.basic.cost3','attack_area','p1',true,false);state.abilityRuntime!.cardState[basic]!.paidManaOnPlay=0;state.players[0]!.mana=1;processAbilityEvent(state,terminal());const d=state.abilityRuntime!.pendingDecision!;expect(d.candidates).toEqual([basic]);const before=state.players[0]!.mana;expect(dispatchAbilityCommand(state,'p1',{type:'choose_target',decisionId:d.id,selectedIds:[basic]}).ok).toBe(true);expect(state.cards.find(c=>c.instanceId===basic)!.zone).toBe('deck');expect(state.players[0]!.mana).toBe(before+6);});
  it('keeps canonical production authoring free of legacy Araya handler routing',()=>{const text=readFileSync('data/authoring/masters/master.araya.json','utf8');for(const needle of ['core.araya-triple-boundary','core.araya-paradox-spiral'])expect(text).not.toContain(needle);});
});
