import { describe, expect, it } from 'vitest';
import { createSeededGameState } from '../../src/tools/seeded-state';
import { loadAuthoringJson } from '../../src/ability/loader';
import {
  dispatchAbilityCommand, initializeAbilityRuntime, isCanonicalGenericPendingDecisionForRestore, isDeferredAbilityRuntimeProvenanceValidForRestore,
  playAbilityCardBatch, processAbilityEvent,
} from '../../src/ability/interpreter';
import {
  getPlayerIdsPresentAtLocation, getPlayerPresenceLocationIds, getPlayerExtraPresences,
  multiPresenceResolutionLocationOptions, multiPresenceTerrainAdvantageAtLocation,
} from '../../src/ability/multi-presence-player-capability';
import { deriveBattleParticipantsFromState } from '../../src/core/combat-resolver';
import type { GameState } from '../../src/schema/game';

const ROOT='master.fixture-multipresence';
const PRESENCE='fixture.phantom';
const S1=`${ROOT}.skill.s1`, S2=`${ROOT}.skill.s2`, ASC=`${ROOT}.skill.ascension`, PAY=`${ROOT}.skill.pay`, MOVE=`${ROOT}.skill.move`;
const LOSS='fixture.presence.loss', DEPLOY='fixture.presence.deploy', MIRROR='fixture.presence.mirror', TAX='fixture.presence.tax';
const SHARED='fixture.presence.shared', TERRAIN='fixture.presence.terrain', SACRIFICE='fixture.presence.sacrifice';
function base(id:string,kind='passive'){return {id,kind,printedClause:id,activation:{},conditions:[],targets:[],effects:[],cost:[],ruleModifiers:[],creates:[],lifecycle:{},responseWindow:{order:'turn_order',passBehavior:'decline_this_window'},limit:{},visibility:{},execution:{mode:'automatic',allowedOperations:[]}} as any;}
function forced(id:string,trigger:string,effect:any){const a=base(id,'forced_trigger');a.activation={trigger};a.effects=[effect];return a;}
function marker(id:string,effect:any){const a=base(id);a.effects=[effect];return a;}
function deploy(){const a=base(DEPLOY,'phase_action');a.activation={phase:'preparation',opens:'controller_action_window'};a.targets=[{id:'battlefield',type:'location',count:{min:1,max:1},constraints:[{type:'any_battlefield'}]}];a.effects=[{type:'multi_presence_deploy',presenceKey:PRESENCE,target:'battlefield'}];return a;}
function sacrifice(){const a=base(SACRIFICE,'phase_action');a.activation={phase:'action',opens:'controller_action_window'};a.effects=[{type:'multi_presence_sacrifice_defeat',presenceKey:PRESENCE}];return a;}
function moveAbility(){const a=base('fixture.move.location','phase_action');a.printedClause='移动至一个地点';a.activation={phase:'action',opens:'controller_action_window',requiresSourceState:'active'};a.targets=[{id:'destination',type:'location',count:{min:1,max:1},constraints:[{type:'any_enabled_location'},{type:'not_location_kind',locationKind:'workshop'}]}];a.effects=[{type:'move_player',to:'destination'}];return a;}
function battlefieldAbility(){const a=base('fixture.battlefield.action','phase_action');a.printedClause='若你位于战场，获得1点魔力';a.activation={phase:'action',opens:'controller_action_window',requiresSourceState:'active'};a.conditions=[{type:'controller_at_battlefield'}];a.effects=[{type:'adjust_mana',amount:1}];return a;}
function archive(){
 const s1=[
   forced(LOSS,'after_controller_loses_battle',{type:'multi_presence_record_battle_loss',presenceKey:PRESENCE}), deploy(),
   forced(MIRROR,'after_controller_enters_location',{type:'multi_presence_mirror_move',presenceKey:PRESENCE}),
   forced(TAX,'after_card_batch_played',{type:'multi_presence_post_play_mana_loss',presenceKey:PRESENCE,numerator:1,denominator:2,rounding:'ceil'}),
 ];
 const s2=[marker(SHARED,{type:'multi_presence_shared_player_rule',presenceKey:PRESENCE})];
 const asc=[marker(TERRAIN,{type:'multi_presence_share_terrain',presenceKey:PRESENCE}),sacrifice()];
 const pay=base('fixture.pay.action','phase_action');pay.activation={phase:'action',opens:'controller_action_window'};pay.effects=[];
 const card=(id:string,abilities:any[],cost=0,power=0)=>({id,name:id,cardType:'master_skill',owner:{type:'master',id:ROOT},cardFace:{typeLabel:'被动',attributes:[],cost,basePower:power},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[],abilities,verification:{implementationStatus:'complete'}});
 return {schemaVersion:'fd-card-authoring-v1',archiveType:'master_skill_card_archive',id:ROOT,name:'Fixture Multi Presence',class:'Master',publicInformation:{type:'master_package',initialMana:4},cards:[card(S1,s1),card(S2,s2),card(ASC,asc),card(PAY,[pay],3,4),card(MOVE,[moveAbility(),battlefieldAbility()])]} as any;
}
function add(state:GameState,definitionId:string,zone='skill',active=false){const instanceId=`${definitionId}:${state.cards.length}`;state.cards.push({instanceId,definitionId,ownerPlayerId:'p1',controllerPlayerId:'p1',zone,visibility:['field','attack_area'].includes(zone)?{scope:'public'}:{scope:'owner_only',ownerPlayerId:'p1'}} as any);state.abilityRuntime!.cardState[instanceId]={active,faceDown:false,playedRound:state.round.roundNumber};return instanceId;}
function setup(){const pack=loadAuthoringJson(archive());expect(pack.report.filter(x=>x.status==='unsupported')).toEqual([]);for(const def of Object.values(pack.cards)) (def as any).ownerId=ROOT;const state=createSeededGameState({activeSeats:[1,2,3]});state.cards=[];state.players[0]!.masterCardId=ROOT;state.players.forEach(p=>{p.mana=10;p.vp=0;});state.players[0]!.locationId='magic_workshop';state.players[1]!.locationId='miyama_town';state.players[2]!.locationId='shinto';initializeAbilityRuntime(state,pack,{seed:20261001});const ids={s1:add(state,S1),s2:add(state,S2),asc:add(state,ASC),pay:add(state,PAY),move:add(state,MOVE,'field',true)};return {state,pack,ids};}
function activate(state:GameState,source:string,abilityId:string){return dispatchAbilityCommand(state,'p1',{type:'activate_ability',cardInstanceId:source,abilityId});}
function deployTo(state:GameState,source:string,locationId:string){state.round.activePhase='preparation';state.round.prioritySeat=state.players[0]!.seat;const start=activate(state,source,DEPLOY);expect(start.ok).toBe(true);const pending=state.abilityRuntime!.pendingDecision;expect(pending?.candidates).toContain(locationId);const done=dispatchAbilityCommand(state,'p1',{type:'choose_target',decisionId:pending!.id,selectedIds:[locationId]});expect(done.ok).toBe(true);return getPlayerExtraPresences(state,'p1')[0]!;}

describe('P3 Alice owner-readiness identity-free multi-presence capability',()=>{
 it('accepts exact privileged shapes and rejects a widened deploy shape',()=>{const good=loadAuthoringJson(archive());expect(good.report.filter(x=>x.status==='unsupported')).toEqual([]);const bad=archive();(bad.cards[0].abilities[1].effects[0] as any).extra=true;const out=loadAuthoringJson(bad);expect(out.cards[S1]!.abilities[1]!.execution.mode).toBe('unsupported');expect(out.report.some(x=>x.reason.includes('Multi-presence'))).toBe(true);});
 it('deploys one extra presence through the real preparation action and blocks deployment after a previous-round loss',()=>{const first=setup();const presence=deployTo(first.state,first.ids.s1,'miyama_town');expect(presence).toMatchObject({playerId:'p1',presenceKey:PRESENCE,locationId:'miyama_town',deployedAtLocationId:'miyama_town',terrainAdvantage:3});expect(getPlayerPresenceLocationIds(first.state,'p1').sort()).toEqual(['magic_workshop','miyama_town'].sort());const blocked=setup();blocked.state.round.roundNumber=1;processAbilityEvent(blocked.state,{id:'loss-r1',type:'after_controller_loses_battle',playerId:'p1',battleResult:{winners:['p2'],loserIds:['p1']}});blocked.state.round.roundNumber=2;blocked.state.round.activePhase='preparation';blocked.state.round.prioritySeat=blocked.state.players[0]!.seat;expect(activate(blocked.state,blocked.ids.s1,DEPLOY).ok).toBe(false);expect(getPlayerExtraPresences(blocked.state,'p1')).toHaveLength(0);});
 it('treats two locations as one logical player for presence/opponent discovery and combat, without duplicating the player',()=>{const {state,ids}=setup();deployTo(state,ids.s1,'miyama_town');expect(getPlayerIdsPresentAtLocation(state,'miyama_town')).toEqual(expect.arrayContaining(['p1','p2']));expect(getPlayerIdsPresentAtLocation(state,'miyama_town').filter(id=>id==='p1')).toHaveLength(1);expect(deriveBattleParticipantsFromState(state,'miyama_town').some(p=>p.playerId==='p1')).toBe(true);state.players[0]!.locationId='shinto';expect(deriveBattleParticipantsFromState(state,'shinto').some(p=>p.playerId==='p1')).toBe(true);expect(multiPresenceResolutionLocationOptions(state,'p1',PRESENCE).sort()).toEqual(['miyama_town','shinto'].sort());});
 it('mirrors primary movement by equal directed distance while an unengaged phantom can move, but does not move an engaged phantom',()=>{const free=setup();deployTo(free.state,free.ids.s1,'miyama_town');free.state.players[1]!.locationId='recon';free.state.players[0]!.locationId='miyama_town';processAbilityEvent(free.state,{id:'move-primary',type:'after_controller_enters_location',playerId:'p1',previousLocationId:'magic_workshop',locationId:'miyama_town',movementKind:'effect'});expect(getPlayerExtraPresences(free.state,'p1')[0]!.locationId).toBe('shinto');const engaged=setup();deployTo(engaged.state,engaged.ids.s1,'miyama_town');engaged.state.players[0]!.locationId='miyama_town';processAbilityEvent(engaged.state,{id:'move-primary-engaged',type:'after_controller_enters_location',playerId:'p1',previousLocationId:'magic_workshop',locationId:'miyama_town',movementKind:'effect'});expect(getPlayerExtraPresences(engaged.state,'p1')[0]!.locationId).toBe('miyama_town');});
 it('binds one server-owned presence location before a location-related ability and moves the selected phantom exactly once',()=>{const {state,ids}=setup();deployTo(state,ids.s1,'miyama_town');state.round.activePhase='action';state.round.prioritySeat=state.players[0]!.seat;const start=activate(state,ids.move,'fixture.move.location');expect(start.ok).toBe(true);const contextDecision=state.abilityRuntime!.pendingDecision!;expect(contextDecision.interaction?.kind).toBe('multi_presence_location_context_v1');expect(contextDecision.candidates.sort()).toEqual(['magic_workshop','miyama_town'].sort());expect(isCanonicalGenericPendingDecisionForRestore(state,contextDecision)).toBe(true);const forged=structuredClone(state);(forged.abilityRuntime!.pendingDecision!.interaction as any).candidateLocationIds[0]='recon';expect(isCanonicalGenericPendingDecisionForRestore(forged,forged.abilityRuntime!.pendingDecision!)).toBe(false);const choosePresence=dispatchAbilityCommand(state,'p1',{type:'choose_target',decisionId:contextDecision.id,selectedIds:['miyama_town']});expect(choosePresence.ok).toBe(true);const moveDecision=state.abilityRuntime!.pendingDecision!;expect(moveDecision.interaction).toBeUndefined();expect(moveDecision.target.id).toBe('destination');expect(moveDecision.candidates).toContain('shinto');const finish=dispatchAbilityCommand(state,'p1',{type:'choose_target',decisionId:moveDecision.id,selectedIds:['shinto']});expect(finish.ok).toBe(true);expect(getPlayerExtraPresences(state,'p1')[0]!.locationId).toBe('shinto');expect(state.players[0]!.locationId).toBe('miyama_town');expect(state.abilityRuntime!.events.filter(e=>e.type==='extra_player_presence_moved')).toHaveLength(1);expect(state.abilityRuntime!.pendingDecision).toBeUndefined();});
 it('keeps a battlefield-gated location ability legal when only the selected phantom satisfies its preflight',()=>{const {state,ids}=setup();deployTo(state,ids.s1,'miyama_town');state.round.activePhase='action';state.round.prioritySeat=state.players[0]!.seat;state.players[0]!.locationId='magic_workshop';state.players[0]!.mana=5;const before=dispatchAbilityCommand(state,'p1',{type:'activate_ability',cardInstanceId:ids.move,abilityId:'fixture.battlefield.action'});expect(before.ok).toBe(true);const d=state.abilityRuntime!.pendingDecision!;expect(d.interaction?.kind).toBe('multi_presence_location_context_v1');expect(d.candidates.sort()).toEqual(['magic_workshop','miyama_town'].sort());const done=dispatchAbilityCommand(state,'p1',{type:'choose_target',decisionId:d.id,selectedIds:['miyama_town']});expect(done.ok).toBe(true);expect(state.players[0]!.mana).toBe(6);expect(state.abilityRuntime!.pendingDecision).toBeUndefined();});
 it('applies the post-play mana tax from actual paid card mana through the real batch path',()=>{const {state,ids}=setup();state.round.activePhase='action';state.round.prioritySeat=state.players[0]!.seat;state.players[0]!.mana=10;playAbilityCardBatch(state,'p1',[{cardInstanceId:ids.pay}]);expect(state.players[0]!.mana).toBe(5);});
 it('shares terrain from all presences when the structural provider is live',()=>{const {state,ids}=setup();deployTo(state,ids.s1,'miyama_town');state.players[0]!.locationId='shinto';(state as any).modeState={...(state as any).modeState,terrainAssignments:{miyama_town:['p2'],shinto:['p1']},terrainAssignmentSlots:{miyama_town:{p2:1},shinto:{p1:0}}};expect(multiPresenceTerrainAdvantageAtLocation(state,'p1','miyama_town')).toBe(6);expect(multiPresenceTerrainAdvantageAtLocation(state,'p1','shinto')).toBe(6);});
 it('sacrifices the phantom first, then defeats players remaining at its old location without self-duplication',()=>{const {state,ids}=setup();deployTo(state,ids.s1,'miyama_town');state.players[0]!.locationId='shinto';state.round.activePhase='action';state.round.prioritySeat=state.players[0]!.seat;const result=activate(state,ids.asc,SACRIFICE);expect(result.ok).toBe(true);expect(getPlayerExtraPresences(state,'p1')).toHaveLength(0);expect(state.abilityRuntime!.battleDefeatRoundByPlayer?.p2).toBe(state.round.roundNumber);expect(state.abilityRuntime!.battleDefeatRoundByPlayer?.p1).toBeUndefined();});
 it('rejects forged restore provenance and keeps the production source identity-free',()=>{const {state,ids}=setup();deployTo(state,ids.s1,'miyama_town');expect(isDeferredAbilityRuntimeProvenanceValidForRestore(state)).toBe(true);const forged=structuredClone(state);forged.abilityRuntime!.extraPlayerPresences![0]!.sourceCardId='forged-source';expect(isDeferredAbilityRuntimeProvenanceValidForRestore(forged)).toBe(false);const fs=require('node:fs');const src=fs.readFileSync('packages/rules/src/ability/multi-presence-player-capability.ts','utf8');for(const needle of ['master.alice','爱丽丝','Queenside Castle','赛博幽灵','幻影爱丽丝','master.fixture-multipresence','core.alice-'])expect(src).not.toContain(needle);});
});