import { describe, expect, it } from 'vitest';
import { createSeededGameState } from '../../src/tools/seeded-state';
import { getEnabledLocations } from '../../src/core/map-engine';
import { loadAuthoringJson } from '../../src/ability/loader';
import { calculateCardPower, effectiveCardPlayCost, executeAbility, initializeAbilityRuntime, isDeferredAbilityRuntimeProvenanceValidForRestore, playAbilityCardBatch, processAbilityEvent } from '../../src/ability/interpreter';
import {
  reconcileVesselCycleVictoryPoints, rememberVesselCyclePlayProvenance, resolveVesselCycleEffect,
  vesselCycleReconBonus, vesselCycleStateForTest,
} from '../../src/ability/vessel-cycle-capability';
import type { GameState } from '../../src/schema/game';

const ROOT='master.fixture-vessel'; const CYCLE='fixture.vessel-cycle';
const TRACK=`${ROOT}.tracker`, RESOLVE=`${ROOT}.resolve`, ROA=`${ROOT}.roa`, ELESIA=`${ROOT}.elesia`, SHIKI=`${ROOT}.shiki`, OVERLOAD=`${ROOT}.overload`, ASC=`${ROOT}.asc`;
const INIT='fixture.vessel.init', SCHEDULE='fixture.vessel.schedule', RESOLVER='fixture.vessel.resolve';
const PROVISION='fixture.vessel.provision', RECON='fixture.vessel.recon', AURA='fixture.vessel.aura', EXCEPTION='fixture.vessel.exception', SQUARE='fixture.vessel.square', LIFE='fixture.vessel.lifecycle', BOIL='fixture.vessel.boil', ASCEND='fixture.vessel.ascend';
function base(id:string,kind='passive'){return {id,kind,printedClause:id,activation:{},conditions:[],targets:[],effects:[],cost:[],ruleModifiers:[],creates:[],lifecycle:{},responseWindow:{order:'turn_order',passBehavior:'decline_this_window'},limit:{},visibility:{},execution:{mode:'automatic',allowedOperations:[]}} as any;}
function forced(id:string,trigger:string,effect:any){const a=base(id,'forced_trigger');a.activation={trigger};a.effects=[effect];return a;}
function marker(id:string,effect:any){const a=base(id);a.effects=[effect];return a;}
function archive(){
 const provision=forced(PROVISION,'game_start',{type:'vessel_cycle_game_start_battlefield_provision',cycleKey:CYCLE,targetDefinitionId:OVERLOAD,temporaryAtEachBattlefield:true});
 const init=forced(INIT,'game_start',{type:'vessel_cycle_initialize',cycleKey:CYCLE,initialVessel:'roa',middleVessel:'elesia',finalVessel:'shiki',firstMaxVp:5,middleMaxVp:10,firstVpMultiplier:2,middleVpDivisor:2,middleVpRounding:'ceil',repeatPenaltyVp:3,lossMargin:5,temporaryDefinitionId:OVERLOAD,ascensionDefinitionId:ASC,temporaryKeep:2});
 const schedule=forced(SCHEDULE,'after_controller_loses_battle',{type:'vessel_cycle_schedule_reincarnation',cycleKey:CYCLE});
 const resolver=forced(RESOLVER,'round_start',{type:'vessel_cycle_resolve_reincarnation',cycleKey:CYCLE});
 const recon=marker(RECON,{type:'vessel_cycle_recon_vp_bonus',cycleKey:CYCLE,vessel:'roa',amount:1});
 const aura=marker(AURA,{type:'vessel_cycle_skill_aura',cycleKey:CYCLE,vessel:'elesia',requiredDefinitionId:OVERLOAD,targetCardType:'master_skill',costDelta:-1,powerDelta:1});
 const exception=marker(EXCEPTION,{type:'vessel_cycle_definition_play_exception',cycleKey:CYCLE,vessel:'shiki',targetDefinitionId:OVERLOAD,requirementType:'skill_zone_mana_at_least',threshold:8});
 const square=base(SQUARE,'phase_action');square.activation={phase:'action',opens:'controller_action_window'};square.effects=[{type:'vessel_cycle_double_active_definition_base_power',cycleKey:CYCLE,vessel:'shiki',targetDefinitionId:OVERLOAD,multiplier:2}];
 const life=forced(LIFE,'on_card_played',{type:'vessel_cycle_played_definition_lifecycle',cycleKey:CYCLE,vessel:'shiki',targetDefinitionId:OVERLOAD,lowManaThreshold:8,lowManaPowerBonus:3,normalClose:true,createTemporaryAtControllerLocation:true});
 const boil=base(BOIL,'optional_trigger');boil.activation={trigger:'after_player_deployed_to_battlefield'};boil.responseWindow={opens:'after_player_deployed_to_battlefield',order:'turn_order',passBehavior:'decline_this_window'};boil.effects=[{type:'vessel_cycle_join_location_definition_cards',cycleKey:CYCLE,targetDefinitionId:OVERLOAD,powerBonus:2,requiresPositiveTerrain:true}];
 const ascend=base(ASCEND,'optional_trigger');ascend.activation={trigger:'round_start'};ascend.responseWindow={opens:'round_start',order:'turn_order',passBehavior:'decline_this_window'};ascend.targets=[{id:'battlefield',type:'location',count:{min:1,max:1},constraints:[{type:'any_battlefield'}]}];ascend.effects=[{type:'vessel_cycle_ascension_round_start',cycleKey:CYCLE,targetDefinitionId:OVERLOAD,target:'battlefield',oncePerRound:true}];
 const card=(id:string,abilities:any[],cost=0,power=0)=>({id,name:id,cardType:'master_skill',owner:{type:'master',id:ROOT},cardFace:{attributes:[],cost,basePower:power},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[{type:'skill_zone_mana_at_least',value:8}],abilities,verification:{implementationStatus:'complete'}});
 return {schemaVersion:'fd-card-authoring-v1',id:ROOT,cards:[card(TRACK,[provision,init,schedule]),card(RESOLVE,[resolver]),card(ROA,[recon]),card(ELESIA,[aura],2,2),card(SHIKI,[exception,square]),card(OVERLOAD,[life,boil],2,4),card(ASC,[ascend])]} as any;
}
function add(state:GameState,definitionId:string,zone='skill',active=false,generatedBy?:string,location?:string){const instanceId=`${definitionId}:p1:${state.cards.length}`;state.cards.push({instanceId,definitionId,ownerPlayerId:'p1',controllerPlayerId:'p1',zone,visibility:['field','attack_area'].includes(zone)?{scope:'public'}:{scope:'owner_only',ownerPlayerId:'p1'},...(generatedBy?{generatedBy}:{})} as any);state.abilityRuntime!.cardState[instanceId]={active,faceDown:false,playedRound:state.round.roundNumber,...(location?{placedAtLocationId:location}: {})};return instanceId;}
function setup(){const pack=loadAuthoringJson(archive());expect(pack.report.filter(e=>e.status==='unsupported')).toEqual([]);const state=createSeededGameState({activeSeats:[1,2,3]});state.cards=[];initializeAbilityRuntime(state,pack,{seed:20261001});state.players[0]!.masterCardId=ROOT;state.players[0]!.mana=30;state.players[0]!.vp=0;state.players[0]!.locationId='miyama_town';(state as any).modeState={...((state as any).modeState??{}),terrainAssignments:{miyama_town:['p1']}};const ids={track:add(state,TRACK),resolve:add(state,RESOLVE),roa:add(state,ROA),elesia:add(state,ELESIA),shiki:add(state,SHIKI),overload:add(state,OVERLOAD),asc:add(state,ASC)};processAbilityEvent(state,{id:'fixture-game-start',type:'game_start',playerId:'p1'});return {state,pack,ids};}
function ability(state:GameState,source:string,id:string){const c=state.cards.find(x=>x.instanceId===source)!;return state.abilityRuntime!.pack.cards[c.definitionId]!.abilities.find(x=>x.id===id)!;}
function exec(state:GameState,source:string,id:string,event?:any,selections:Record<string,string[]>={}){executeAbility(state,{controllerId:'p1',sourceCardId:source,abilityId:id,variables:{},selections,event});}
function lossEvent(state:GameState,own=0,win=5){return {id:`loss-${state.round.roundNumber}`,type:'after_controller_loses_battle',playerId:'p1',battleResult:{winners:['p2'],loserIds:['p1']},battleParticipantPowers:{p1:own,p2:win}} as any;}
function advance(state:GameState,ids:any,gained:number){state.players[0]!.vp+=gained;reconcileVesselCycleVictoryPoints(state);exec(state,ids.track,SCHEDULE,lossEvent(state));state.round.roundNumber++;exec(state,ids.resolve,RESOLVER,{id:`round-${state.round.roundNumber}`,type:'round_start',playerId:'p1'});}

describe('P3 Akasha owner-readiness identity-free vessel-cycle capability',()=>{
 it('fails closed when the battlefield-provision privileged shape is widened',()=>{const bad=archive();const provision=bad.cards[0].abilities.find((a:any)=>a.id===PROVISION);provision.effects[0].temporaryAtEachBattlefield=false;const loaded=loadAuthoringJson(bad);expect(loaded.cards[TRACK]!.abilities.find(a=>a.id===PROVISION)!.execution.mode).toBe('unsupported');expect(loaded.report.some(e=>e.reason.includes('Vessel-cycle'))).toBe(true);});
 it('provisions exactly one generated temporary definition at each enabled battlefield and is idempotent on repeated game-start delivery',()=>{const {state,ids}=setup();const battlefields=getEnabledLocations(state.map,state.locationConfig).filter((location:any)=>location.tags?.includes('battlefield')).map((location:any)=>location.id);const generated=state.cards.filter(c=>c.definitionId===OVERLOAD&&c.generatedBy===ids.track&&c.zone==='field');expect(generated).toHaveLength(battlefields.length);expect(new Set(generated.map(c=>state.abilityRuntime!.cardState[c.instanceId]!.placedAtLocationId))).toEqual(new Set(battlefields));for(const c of generated){expect(c.ownerPlayerId).toBe('p1');expect(c.controllerPlayerId).toBe('p1');expect(state.abilityRuntime!.cardState[c.instanceId]).toMatchObject({active:true,faceDown:false,playedRound:state.round.roundNumber});}processAbilityEvent(state,{id:'fixture-game-start-repeat',type:'game_start',playerId:'p1'});expect(state.cards.filter(c=>c.definitionId===OVERLOAD&&c.generatedBy===ids.track&&c.zone==='field')).toHaveLength(battlefields.length);});
 it('accepts exact generic shapes and fails closed for widened privileged shapes',()=>{const good=loadAuthoringJson(archive());expect(good.report.filter(e=>e.status==='unsupported')).toEqual([]);const bad=archive();bad.cards[0].abilities[0].effects[0].firstMaxVp=6;const out=loadAuthoringJson(bad);expect(out.cards[TRACK]!.abilities[0]!.execution.mode).toBe('unsupported');expect(out.report.some(e=>e.reason.includes('Vessel-cycle'))).toBe(true);});
 it('initializes Roa, records only positive VP deltas, and schedules only authoritative >=5 loss margin',()=>{const {state,ids}=setup();expect(vesselCycleStateForTest(state,'p1',CYCLE)).toMatchObject({current:'roa',points:0});state.players[0]!.vp=4;reconcileVesselCycleVictoryPoints(state);expect(vesselCycleStateForTest(state,'p1',CYCLE).points).toBe(4);exec(state,ids.track,SCHEDULE,lossEvent(state,1,5));expect(vesselCycleStateForTest(state,'p1',CYCLE).pendingRound).toBeUndefined();exec(state,ids.track,SCHEDULE,lossEvent(state,0,5));expect(vesselCycleStateForTest(state,'p1',CYCLE).pendingRound).toBe(2);});
 it('resolves 0-5/6-10/11+ thresholds using Roa x2 and Elesia ceil-half and activates ultimate after all vessels',()=>{const {state,ids}=setup();advance(state,ids,3);expect(vesselCycleStateForTest(state,'p1',CYCLE).current).toBe('elesia');advance(state,ids,21);expect(vesselCycleStateForTest(state,'p1',CYCLE)).toMatchObject({current:'shiki',ultimate:true});});
 it('applies same-vessel -3 VP and keeps exactly two generated temporary definition cards on reincarnation',()=>{const {state,ids}=setup();state.players[0]!.vp=2;for(let i=0;i<4;i++)add(state,OVERLOAD,'field',true,ids.overload,i%2?'shinto':'miyama_town');reconcileVesselCycleVictoryPoints(state);exec(state,ids.track,SCHEDULE,lossEvent(state));state.round.roundNumber++;exec(state,ids.resolve,RESOLVER,{id:'round-repeat',type:'round_start',playerId:'p1'});expect(state.players[0]!.vp).toBe(0);expect(state.cards.filter(c=>c.definitionId===OVERLOAD&&c.generatedBy&&c.zone!=='removed_from_game')).toHaveLength(2);});
 it('exposes Roa recon +1 only in the matching vessel',()=>{const {state,ids}=setup();expect(vesselCycleReconBonus(state,'p1')).toBe(1);advance(state,ids,3);expect(vesselCycleReconBonus(state,'p1')).toBe(0);});
 it('applies Elesia skill +1 power/-1 cost only while the controller owns a live Overload',()=>{const {state,ids}=setup();advance(state,ids,3);expect(effectiveCardPlayCost(state,'p1',ids.elesia)).toBe(1);expect(calculateCardPower(state,ids.elesia).value).toBe(3);for(const c of state.cards.filter(c=>c.definitionId===OVERLOAD&&!['discard','removed_from_game'].includes(c.zone))) c.zone='discard';expect(effectiveCardPlayCost(state,'p1',ids.elesia)).toBe(2);expect(calculateCardPower(state,ids.elesia).value).toBe(2);});
 it('uses the real play gate for exact Shiki exception and seals pre-payment mana for low-mana provenance',()=>{const blocked=setup();blocked.state.round.activePhase='action';blocked.state.round.prioritySeat=blocked.state.players[0]!.seat;blocked.state.players[0]!.mana=7;expect(()=>playAbilityCardBatch(blocked.state,'p1',[{cardInstanceId:blocked.ids.overload}])).toThrow();const low=setup();advance(low.state,low.ids,3);advance(low.state,low.ids,21);low.state.round.activePhase='action';low.state.round.prioritySeat=low.state.players[0]!.seat;low.state.players[0]!.mana=7;playAbilityCardBatch(low.state,'p1',[{cardInstanceId:low.ids.overload}]);expect(low.state.players[0]!.mana).toBe(5);const lowCard=low.state.cards.find(x=>x.instanceId===low.ids.overload)!;expect(lowCard.zone).toBe('field');expect(calculateCardPower(low.state,low.ids.overload).value).toBe(7);const normal=setup();advance(normal.state,normal.ids,3);advance(normal.state,normal.ids,21);normal.state.round.activePhase='action';normal.state.round.prioritySeat=normal.state.players[0]!.seat;normal.state.players[0]!.mana=8;playAbilityCardBatch(normal.state,'p1',[{cardInstanceId:normal.ids.overload}]);expect(normal.state.players[0]!.mana).toBe(6);expect(normal.state.cards.find(x=>x.instanceId===normal.ids.overload)!.zone).toBe('skill');expect(normal.state.cards.filter(x=>x.definitionId===OVERLOAD&&x.generatedBy===normal.ids.overload&&x.zone==='field')).toHaveLength(1);});
 it('normal Overload play closes the physical card and creates one generated battlefield copy',()=>{const {state,ids}=setup();const c=state.cards.find(x=>x.instanceId===ids.overload)!;c.zone='attack_area';state.abilityRuntime!.cardState[ids.overload]={active:true,faceDown:false,playedRound:1,paidManaOnPlay:2};exec(state,ids.overload,LIFE,{id:'play-normal',type:'on_card_played',playerId:'p1',sourceCardId:ids.overload});expect(c.zone).toBe('skill');const temps=state.cards.filter(x=>x.definitionId===OVERLOAD&&x.generatedBy===ids.overload&&x.zone==='field');expect(temps).toHaveLength(1);expect(state.abilityRuntime!.cardState[temps[0]!.instanceId]!.placedAtLocationId).toBe('miyama_town');});
 it('Shiki Square atomically pays printed costs of all active Overloads and doubles exact physical base power',()=>{const {state,ids}=setup();advance(state,ids,3);advance(state,ids,21);const o1=state.cards.find(x=>x.instanceId===ids.overload)!;o1.zone='attack_area';state.abilityRuntime!.cardState[ids.overload]={active:true,faceDown:false,playedRound:state.round.roundNumber};const o2=add(state,OVERLOAD,'attack_area',true);const before=state.players[0]!.mana;exec(state,ids.shiki,SQUARE);expect(state.players[0]!.mana).toBe(before-4);expect(calculateCardPower(state,ids.overload).value).toBe(8);expect(calculateCardPower(state,o2).value).toBe(8);});
 it('joins only matching generated cards at the deployed battlefield with +2 and ascension creates at most once per climax round',()=>{const {state,ids}=setup();const here=add(state,OVERLOAD,'field',true,ids.overload,'miyama_town');const away=add(state,OVERLOAD,'field',true,ids.overload,'shinto');exec(state,ids.overload,BOIL,{id:'deploy',type:'after_player_deployed_to_battlefield',playerId:'p1',locationId:'miyama_town'});expect(state.cards.find(c=>c.instanceId===here)!.zone).toBe('attack_area');expect(calculateCardPower(state,here).value).toBe(6);expect(state.cards.find(c=>c.instanceId===away)!.zone).toBe('field');advance(state,ids,3);advance(state,ids,21);state.round.roundNumber=9;(state as any).modeState={currentSituationIsClimax:true};exec(state,ids.asc,ASCEND,{id:'climax',type:'round_start',playerId:'p1'},{battlefield:['shinto']});expect(state.cards.filter(c=>c.definitionId===OVERLOAD&&c.generatedBy===ids.asc&&c.zone==='field')).toHaveLength(1);expect(()=>exec(state,ids.asc,ASCEND,{id:'climax-again',type:'round_start',playerId:'p1'},{battlefield:['miyama_town']})).toThrow();});
 it('rejects forged restored vessel/current-provider provenance',()=>{const {state}=setup();expect(isDeferredAbilityRuntimeProvenanceValidForRestore(state)).toBe(true);const forged=structuredClone(state);const bag=forged.abilityRuntime!.structuredPlayerFlagsByPlayer!.p1!;bag['__fd_vessel_cycle:fixture.vessel-cycle:current']='intruder';expect(isDeferredAbilityRuntimeProvenanceValidForRestore(forged)).toBe(false);const forgedProvider=structuredClone(state);forgedProvider.abilityRuntime!.structuredPlayerFlagsByPlayer!.p1!['__fd_vessel_cycle:fixture.vessel-cycle:providerSource']='forged-source';expect(isDeferredAbilityRuntimeProvenanceValidForRestore(forgedProvider)).toBe(false);});
 it('does not join location Overloads without positive terrain advantage',()=>{const {state,ids}=setup();(state as any).modeState={...((state as any).modeState??{}),terrainAssignments:{miyama_town:['p2']}};const here=add(state,OVERLOAD,'field',true,ids.overload,'miyama_town');exec(state,ids.overload,BOIL,{id:'deploy-no-terrain',type:'after_player_deployed_to_battlefield',playerId:'p1',locationId:'miyama_town'});expect(state.cards.find(c=>c.instanceId===here)!.zone).toBe('field');});
 it('expires vessel-cycle +3 and base-power x2 authority at the next round',()=>{const {state,ids}=setup();advance(state,ids,3);advance(state,ids,21);state.players[0]!.mana=7;rememberVesselCyclePlayProvenance(state,'p1',ids.overload,7);const c=state.cards.find(x=>x.instanceId===ids.overload)!;c.zone='attack_area';state.abilityRuntime!.cardState[ids.overload]={active:true,faceDown:false,playedRound:state.round.roundNumber,paidManaOnPlay:2};exec(state,ids.overload,LIFE,{id:'low-round',type:'on_card_played',playerId:'p1',sourceCardId:ids.overload});expect(calculateCardPower(state,ids.overload).value).toBe(7);const o2=add(state,OVERLOAD,'attack_area',true);exec(state,ids.shiki,SQUARE);expect(calculateCardPower(state,o2).value).toBe(8);state.round.roundNumber++;expect(calculateCardPower(state,ids.overload).value).toBe(4);expect(calculateCardPower(state,o2).value).toBe(4);});
 it('provisions one live ascension definition after all three vessels if no live copy exists',()=>{const {state,ids}=setup();state.cards.find(c=>c.instanceId===ids.asc)!.zone='removed_from_game';advance(state,ids,3);advance(state,ids,21);expect(vesselCycleStateForTest(state,'p1',CYCLE).ultimate).toBe(true);const live=state.cards.filter(c=>c.ownerPlayerId==='p1'&&c.definitionId===ASC&&c.zone!=='removed_from_game');expect(live).toHaveLength(1);expect(live[0]!.zone).toBe('skill');}); it('keeps production capability source free of fixture/Akasha identities',()=>{const fs=require('node:fs');const src=fs.readFileSync('packages/rules/src/ability/vessel-cycle-capability.ts','utf8');for(const needle of ['master.akasha','阿卡夏','master.fixture-vessel','core.akasha-'])expect(src).not.toContain(needle);});
});
