import { describe, expect, it } from 'vitest';
import { createSeededGameState } from '../../src/tools/seeded-state';
import { loadAuthoringJson } from '../../src/ability/loader';
import { calculateCardPower, dispatchAbilityCommand, initializeAbilityRuntime, isDeferredAbilityRuntimeProvenanceValidForRestore, processAbilityEvent } from '../../src/ability/interpreter';
import type { GameState } from '../../src/schema/game';
import { resolveBattlefield } from '../../src/core/combat-resolver';

const ROOT='master.fixture-ascension-event', SERVANT='servant.fixture-ascension-event', ASC=`${ROOT}.skill.ascension`, UNLOCK=`${SERVANT}.skill.unlock`, BASIC=`${SERVANT}.basic.one`, OTHER=`${SERVANT}.attack.one`, EVENT='event.fixture.applause';
const UNLOCK_A='fixture.unlock', SEAL_A='fixture.ascension.seals', EVENT_A='fixture.ascension.event-power';
function base(id:string,kind='forced_trigger'){return {id,kind,printedClause:id,activation:{},conditions:[],targets:[],effects:[],cost:[],ruleModifiers:[],creates:[],lifecycle:{},responseWindow:{order:'turn_order',passBehavior:'decline_this_window'},limit:{},visibility:{},execution:{mode:'automatic',allowedOperations:[]}} as any;}
function archive(){
 const unlock=base(UNLOCK_A,'phase_action');unlock.activation={phase:'action',opens:'controller_action_window'};unlock.effects=[{type:'unlock_controller_master_ascension'}];
 const seal=base(SEAL_A);seal.activation={trigger:'after_master_ascension_unlocked'};seal.effects=[{type:'ascension_unlock_opponents_lose_command_seals',amount:2,floor:0}];
 const event=base(EVENT_A);event.activation={trigger:'event_activated',eventDefinitionId:EVENT};event.effects=[{type:'named_event_basic_attack_power_bonus',amount:4,duration:'while_event_active'}];
 const card=(id:string,cardType:string,owner:any,abilities:any[],basePower=0,extra:any={})=>({id,name:id,cardType,owner,cardFace:{typeLabel:'fixture',attributes:['魔术'],cost:0,basePower},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[],abilities,verification:{implementationStatus:'complete'},...extra});
 return {schemaVersion:'fd-card-authoring-v1',archiveType:'master_skill_card_archive',id:ROOT,name:'Fixture',class:'Master',publicInformation:{type:'master_package',initialMana:4},cards:[
  card(UNLOCK,'servant_skill',{type:'servant',id:SERVANT},[unlock]),
  card(ASC,'master_skill',{type:'master',id:ROOT},[seal,event],0,{initialPlacement:'outside_game'}),
  card(BASIC,'basic_attack',{type:'servant',id:SERVANT},[],2),
  card(OTHER,'servant_attack',{type:'servant',id:SERVANT},[],2),
 ]} as any;
}
function add(state:GameState,definitionId:string,owner:string,zone:any='skill'){const instanceId=`${owner}:${definitionId}:${state.cards.length}`;state.cards.push({instanceId,definitionId,ownerPlayerId:owner,controllerPlayerId:owner,zone,visibility:zone==='attack_area'?{scope:'public'}:{scope:'owner_only',ownerPlayerId:owner}} as any);state.abilityRuntime!.cardState[instanceId]={active:zone==='attack_area',faceDown:false,playedRound:state.round.roundNumber};return instanceId;}
function setup(){const pack=loadAuthoringJson(archive());expect(pack.report.filter(x=>x.status==='unsupported')).toEqual([]);for(const def of Object.values(pack.cards))(def as any).ownerId=(def as any).cardType==='master_skill'?ROOT:SERVANT;const state=createSeededGameState({activeSeats:[1,2,3]});state.cards=[];state.players[0]!.masterCardId=ROOT;state.players[0]!.servantCardId=SERVANT;initializeAbilityRuntime(state,pack,{seed:20261001});(state.players[1] as any).commandSpells=3;(state.players[2] as any).commandSpells=1;const unlock=add(state,UNLOCK,'p1');const basic=add(state,BASIC,'p1','attack_area');const other=add(state,OTHER,'p1','attack_area');state.round.activePhase='action';state.round.prioritySeat=state.players[0]!.seat;return {state,ids:{unlock,basic,other}};}
function unlock(state:GameState,id:string){expect(dispatchAbilityCommand(state,'p1',{type:'activate_ability',cardInstanceId:id,abilityId:UNLOCK_A}).ok).toBe(true);return state.cards.find(c=>c.definitionId===ASC)!;}
function activateEvent(state:GameState,id='evt-rule',eventId=EVENT){state.eventPlacements.push({locationId:'shinto',eventCardId:eventId,ruleInstanceId:id,visibility:{scope:'public'}} as any);processAbilityEvent(state,{id:`activation:${id}`,type:'event_activated',sourceCardId:id,revealedKind:'event',revealedId:eventId,locationId:'shinto'});}

describe('P3 Amakusa ascension event-power readiness capability',()=>{
 it('admits only the two exact privileged whole-ability shapes',()=>{const good=loadAuthoringJson(archive());expect(good.report.filter(x=>x.status==='unsupported')).toEqual([]);const bad=archive();(bad.cards[1].abilities[1].effects[0] as any).amount=5;const out=loadAuthoringJson(bad);expect(out.cards[ASC]!.abilities[1]!.execution.mode).toBe('unsupported');expect(out.report.some(x=>x.reason.includes('ascension event/seal'))).toBe(true);});
 it('settles opponent seal loss once from the authoritative ascension unlock and floors at zero',()=>{const {state,ids}=setup();const asc=unlock(state,ids.unlock);expect(asc.zone).toBe('skill');expect((state.players[1] as any).commandSpells).toBe(1);expect((state.players[2] as any).commandSpells).toBe(0);expect(state.abilityRuntime!.events.filter(e=>e.type==='command_seals_adjusted')).toHaveLength(2);expect(dispatchAbilityCommand(state,'p1',{type:'activate_ability',cardInstanceId:ids.unlock,abilityId:UNLOCK_A}).ok).toBe(true);expect((state.players[1] as any).commandSpells).toBe(1);expect((state.players[2] as any).commandSpells).toBe(0);expect(state.abilityRuntime!.events.filter(e=>e.type==='command_seals_adjusted')).toHaveLength(2);});
 it('binds exact event activation to +4 Power for controller basic attacks only',()=>{const {state,ids}=setup();unlock(state,ids.unlock);expect(calculateCardPower(state,ids.basic).value).toBe(2);activateEvent(state);expect(calculateCardPower(state,ids.basic).value).toBe(6);expect(calculateCardPower(state,ids.other).value).toBe(2);const p2=add(state,BASIC,'p2','attack_area');expect(calculateCardPower(state,p2).value).toBe(2);expect(isDeferredAbilityRuntimeProvenanceValidForRestore(state)).toBe(true);});
 it('activates a hidden exact event before the same battle Power snapshot',()=>{const a=setup();unlock(a.state,a.ids.unlock);a.state.players[0]!.locationId='miyama_town';a.state.players[1]!.locationId='miyama_town';a.state.eventPlacements=[{locationId:'miyama_town',eventCardId:EVENT,ruleInstanceId:'hidden-exact',visibility:{scope:'hidden_until_trigger'}} as any];const b=structuredClone(a.state);b.eventPlacements=[{locationId:'miyama_town',eventCardId:'event.fixture.other',ruleInstanceId:'hidden-other',visibility:{scope:'hidden_until_trigger'}} as any];const exact=resolveBattlefield(a.state,{battlefieldId:'miyama_town',revealHiddenEvents:true}).nextState;const other=resolveBattlefield(b,{battlefieldId:'miyama_town',revealHiddenEvents:true}).nextState;expect(exact.abilityRuntime!.masterAscensionEventPowerByPlayer?.p1?.eventDefinitionId).toBe(EVENT);expect(calculateCardPower(exact,a.ids.basic).value).toBe(6);expect(calculateCardPower(other,a.ids.basic).value).toBe(2);const ep=exact.battleResults.at(-1)!.participantBreakdowns.find(x=>x.playerId==='p1')!.effectivePower;const op=other.battleResults.at(-1)!.participantBreakdowns.find(x=>x.playerId==='p1')!.effectivePower;expect(ep-op).toBe(4);}); it('does not activate on a different event definition',()=>{const {state,ids}=setup();unlock(state,ids.unlock);activateEvent(state,'wrong-rule','event.fixture.other');expect(calculateCardPower(state,ids.basic).value).toBe(2);expect(state.abilityRuntime!.masterAscensionEventPowerByPlayer?.p1).toBeUndefined();});
 it('cleans event Power authority at round end',()=>{const {state,ids}=setup();unlock(state,ids.unlock);activateEvent(state);expect(calculateCardPower(state,ids.basic).value).toBe(6);processAbilityEvent(state,{id:'round-end-fixture',type:'round_end',playerId:'p1'});expect(state.abilityRuntime!.masterAscensionEventPowerByPlayer?.p1).toBeUndefined();});
 it('fails restore for forged event placement or ascension provider provenance without identity routing',()=>{const {state,ids}=setup();const asc=unlock(state,ids.unlock);activateEvent(state);expect(isDeferredAbilityRuntimeProvenanceValidForRestore(state)).toBe(true);const forgedEvent=structuredClone(state);forgedEvent.eventPlacements[0]!.eventCardId='event.fixture.other';expect(isDeferredAbilityRuntimeProvenanceValidForRestore(forgedEvent)).toBe(false);const forgedProvider=structuredClone(state);forgedProvider.cards.find(c=>c.instanceId===asc.instanceId)!.controllerPlayerId='p2';expect(isDeferredAbilityRuntimeProvenanceValidForRestore(forgedProvider)).toBe(false);const forgedUnlock=structuredClone(state);forgedUnlock.cards.find(c=>c.instanceId===asc.instanceId)!.generatedBy='forged';expect(isDeferredAbilityRuntimeProvenanceValidForRestore(forgedUnlock)).toBe(false);const servantDrift=structuredClone(state);servantDrift.players.find(p=>p.id==='p1')!.servantCardId='servant.other';expect(isDeferredAbilityRuntimeProvenanceValidForRestore(servantDrift)).toBe(false);const forgedRecord=structuredClone(state);forgedRecord.abilityRuntime!.masterAscensionEventPowerByPlayer!.p1!.eventRuleInstanceId='forged';expect(isDeferredAbilityRuntimeProvenanceValidForRestore(forgedRecord)).toBe(false);const fs=require('node:fs');const src=fs.readFileSync('packages/rules/src/ability/master-ascension-event-power-capability.ts','utf8');for(const needle of ['master.amakusa','天草四郎','过去的裁定者','开演之时已至','core.amakusa-'])expect(src).not.toContain(needle);});
});