import { describe, expect, it } from 'vitest';
import { createSeededGameState } from '../../src/tools/seeded-state';
import { loadAuthoringJson } from '../../src/ability/loader';
import { dispatchAbilityCommand, initializeAbilityRuntime, isDeferredAbilityRuntimeProvenanceValidForRestore, processAbilityEvent } from '../../src/ability/interpreter';
import type { GameState } from '../../src/schema/game';

const ROOT='master.fixture-linked-copy', SERVANT='servant.fixture-linked-copy', REL='fixture.copy-covenant';
const INIT_CARD=`${ROOT}.skill.init`, RULE_CARD=`${ROOT}.skill.rules`, COPY_CARD=`${ROOT}.skill.copy`, MEMBER_SKILL=`${SERVANT}.skill.s1`;
const INIT='fixture.copy.init', RULES='fixture.copy.rules', COPY='fixture.copy.action', MEMBER_ABILITY='fixture.member.action';
function base(id:string,kind='passive'){return {id,kind,printedClause:id,activation:{},conditions:[],targets:[],effects:[],cost:[],ruleModifiers:[],creates:[],lifecycle:{},responseWindow:{order:'turn_order',passBehavior:'decline_this_window'},limit:{},visibility:{},execution:{mode:'automatic',allowedOperations:[]}} as any;}
function archive(){
 const init=base(INIT,'forced_trigger');init.activation={trigger:'game_start'};init.effects=[{type:'linked_role_initialize',relationshipKey:REL,leaderRoleKey:'leader',memberRoleKey:'member',memberSelector:'next_seat'}];
 const rules=base(RULES);rules.effects=[{type:'linked_role_member_rules',relationshipKey:REL,leaderRoleKey:'leader',memberRoleKey:'member',entryCommandSealCost:1,entryOnlyBeforeClimax:true,manaContributionAmount:1,manaContributionMaxPerRound:1,requireDifferentBattlefields:true}];
 const copy=base(COPY,'phase_action');copy.activation={phase:'action',opens:'controller_action_window'};copy.targets=[{id:'member_revealed_servant_skill',type:'card_instance',scope:{zone:'skill',owner:'any',controller:'any'},count:{min:1,max:1},constraints:[]}];copy.effects=[{type:'linked_role_copy_revealed_member_servant_skill',relationshipKey:REL,target:'member_revealed_servant_skill'}];
 const member=base(MEMBER_ABILITY,'phase_action');member.activation={phase:'action',opens:'controller_action_window'};
 const masterCard=(id:string,abilities:any[])=>({id,name:id,cardType:'master_skill',owner:{type:'master',id:ROOT},cardFace:{typeLabel:'魔术',attributes:[],cost:0,basePower:0},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[],abilities,verification:{implementationStatus:'complete'}});
 const servantCard={id:MEMBER_SKILL,name:'member skill',cardType:'servant_skill',owner:{type:'servant',id:SERVANT},cardFace:{typeLabel:'魔术',attributes:[],cost:0,basePower:1},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[],abilities:[member],verification:{implementationStatus:'complete'}};
 return {schemaVersion:'fd-card-authoring-v1',archiveType:'master_skill_card_archive',id:ROOT,name:'Fixture',class:'Master',publicInformation:{type:'master_package',initialMana:4},cards:[masterCard(INIT_CARD,[init]),masterCard(RULE_CARD,[rules]),masterCard(COPY_CARD,[copy]),servantCard]} as any;
}
function add(state:GameState,definitionId:string,owner:string){const instanceId=`${owner}:${definitionId}:${state.cards.length}`;state.cards.push({instanceId,definitionId,ownerPlayerId:owner,controllerPlayerId:owner,zone:'skill',visibility:{scope:'owner_only',ownerPlayerId:owner}} as any);state.abilityRuntime!.cardState[instanceId]={active:false,faceDown:false,playedRound:state.round.roundNumber};return instanceId;}
function setup(revealed=true){const pack=loadAuthoringJson(archive());expect(pack.report.filter(x=>x.status==='unsupported')).toEqual([]);for(const def of Object.values(pack.cards)){(def as any).ownerId=(def as any).cardType==='servant_skill'?SERVANT:ROOT;}const state=createSeededGameState({activeSeats:[1,2,3]});state.cards=[];state.players[0]!.masterCardId=ROOT;state.players[1]!.servantCardId=SERVANT;initializeAbilityRuntime(state,pack,{seed:20261001});if(revealed)state.abilityRuntime!.revealedServants.push('p2');const ids={init:add(state,INIT_CARD,'p1'),rules:add(state,RULE_CARD,'p1'),copy:add(state,COPY_CARD,'p1'),original:add(state,MEMBER_SKILL,'p2')};processAbilityEvent(state,{id:'copy-game-start',type:'game_start',playerId:'p1'});state.round.activePhase='action';state.round.prioritySeat=state.players[0]!.seat;return {state,ids};}
function activeMember(state:GameState){return state.abilityRuntime!.structuredPlayerFlagsByPlayer?.p2?.[`__fd_linked_role:${REL}:memberLeader`] === 'p1';}

describe('P3 Amakusa member-skill-copy readiness capability',()=>{
 it('admits only the exact privileged whole-ability shape',()=>{const good=loadAuthoringJson(archive());expect(good.report.filter(x=>x.status==='unsupported')).toEqual([]);const bad=archive();(bad.cards[2].abilities[0].effects[0] as any).extra=true;const out=loadAuthoringJson(bad);expect(out.cards[COPY_CARD]!.abilities[0]!.execution.mode).toBe('unsupported');expect(out.report.some(x=>x.reason.includes('skill-copy'))).toBe(true);});
 it('offers only revealed active-member servant skills and creates an owner-bound temporary copy',()=>{const {state,ids}=setup();const started=dispatchAbilityCommand(state,'p1',{type:'activate_ability',cardInstanceId:ids.copy,abilityId:COPY});expect(started.ok).toBe(true);const decision=state.abilityRuntime!.pendingDecision!;expect(decision.candidates).toEqual([ids.original]);expect(dispatchAbilityCommand(state,'p1',{type:'choose_target',decisionId:decision.id,selectedIds:[ids.original]}).ok).toBe(true);const copies=Object.values(state.abilityRuntime!.linkedRoleSkillCopies??{});expect(copies).toHaveLength(1);const copy=state.cards.find(c=>c.instanceId===copies[0]!.copyCardInstanceId)!;expect(copy.definitionId).toBe(MEMBER_SKILL);expect(copy.ownerPlayerId).toBe('p1');expect(copy.controllerPlayerId).toBe('p1');expect(copy.zone).toBe('skill');expect(copy.generatedBy).toBe(ids.copy);expect(activeMember(state)).toBe(true);expect(isDeferredAbilityRuntimeProvenanceValidForRestore(state)).toBe(true);});
 it('does not expose a hidden servant skill',()=>{const {state,ids}=setup(false);expect(dispatchAbilityCommand(state,'p1',{type:'activate_ability',cardInstanceId:ids.copy,abilityId:COPY}).ok).toBe(false);expect(state.abilityRuntime!.linkedRoleSkillCopies).toBeUndefined();});
 it('using the copy locks the exact original for the round and removes active membership while preserving ever history',()=>{const {state,ids}=setup();expect(dispatchAbilityCommand(state,'p1',{type:'activate_ability',cardInstanceId:ids.copy,abilityId:COPY}).ok).toBe(true);let d=state.abilityRuntime!.pendingDecision!;expect(dispatchAbilityCommand(state,'p1',{type:'choose_target',decisionId:d.id,selectedIds:[ids.original]}).ok).toBe(true);const copyId=Object.keys(state.abilityRuntime!.linkedRoleSkillCopies!)[0]!;expect(dispatchAbilityCommand(state,'p1',{type:'play_card',cardInstanceId:copyId}).ok).toBe(true);expect(state.abilityRuntime!.linkedRoleOriginalSkillLocks?.[ids.original]).toBe(state.round.roundNumber);expect(activeMember(state)).toBe(false);expect(state.abilityRuntime!.structuredPlayerFlagsByPlayer?.p2?.[`__fd_linked_role:${REL}:ever`]).toBe(true);state.round.prioritySeat=state.players[1]!.seat;expect(dispatchAbilityCommand(state,'p2',{type:'play_card',cardInstanceId:ids.original}).ok).toBe(false);expect(isDeferredAbilityRuntimeProvenanceValidForRestore(state)).toBe(true);});
 it('expires temporary copies and original-use locks at round end',()=>{const {state,ids}=setup();dispatchAbilityCommand(state,'p1',{type:'activate_ability',cardInstanceId:ids.copy,abilityId:COPY});const d=state.abilityRuntime!.pendingDecision!;dispatchAbilityCommand(state,'p1',{type:'choose_target',decisionId:d.id,selectedIds:[ids.original]});const copyId=Object.keys(state.abilityRuntime!.linkedRoleSkillCopies!)[0]!;dispatchAbilityCommand(state,'p1',{type:'play_card',cardInstanceId:copyId});processAbilityEvent(state,{id:'copy-round-end',type:'round_end',playerId:'p1'});expect(state.cards.some(c=>c.instanceId===copyId)).toBe(false);expect(state.abilityRuntime!.linkedRoleSkillCopies?.[copyId]).toBeUndefined();expect(state.abilityRuntime!.linkedRoleOriginalSkillLocks?.[ids.original]).toBeUndefined();});
 it('fails restore when original servant-skill controller or current-servant provenance is forged',()=>{const {state,ids}=setup();dispatchAbilityCommand(state,'p1',{type:'activate_ability',cardInstanceId:ids.copy,abilityId:COPY});const d=state.abilityRuntime!.pendingDecision!;dispatchAbilityCommand(state,'p1',{type:'choose_target',decisionId:d.id,selectedIds:[ids.original]});expect(isDeferredAbilityRuntimeProvenanceValidForRestore(state)).toBe(true);const wrongController=structuredClone(state);wrongController.cards.find(c=>c.instanceId===ids.original)!.controllerPlayerId='p3';expect(isDeferredAbilityRuntimeProvenanceValidForRestore(wrongController)).toBe(false);const nonServant=structuredClone(state);const copyId=Object.keys(nonServant.abilityRuntime!.linkedRoleSkillCopies!)[0]!;nonServant.cards.find(c=>c.instanceId===ids.original)!.definitionId=COPY_CARD;nonServant.cards.find(c=>c.instanceId===copyId)!.definitionId=COPY_CARD;expect(isDeferredAbilityRuntimeProvenanceValidForRestore(nonServant)).toBe(false);const wrongServant=structuredClone(state);wrongServant.players.find(p=>p.id==='p2')!.servantCardId='servant.other';expect(isDeferredAbilityRuntimeProvenanceValidForRestore(wrongServant)).toBe(false);});
 it('fails restore validation for forged copy provenance and contains no Amakusa identity routing',()=>{const {state,ids}=setup();dispatchAbilityCommand(state,'p1',{type:'activate_ability',cardInstanceId:ids.copy,abilityId:COPY});const d=state.abilityRuntime!.pendingDecision!;dispatchAbilityCommand(state,'p1',{type:'choose_target',decisionId:d.id,selectedIds:[ids.original]});expect(isDeferredAbilityRuntimeProvenanceValidForRestore(state)).toBe(true);const forged=structuredClone(state);const copyId=Object.keys(forged.abilityRuntime!.linkedRoleSkillCopies!)[0]!;forged.cards.find(c=>c.instanceId===copyId)!.generatedBy='forged';expect(isDeferredAbilityRuntimeProvenanceValidForRestore(forged)).toBe(false);const fs=require('node:fs');const src=fs.readFileSync('packages/rules/src/ability/linked-role-member-skill-copy-capability.ts','utf8');for(const needle of ['master.amakusa','天草四郎','绝罚','absolute-punishment','core.amakusa-'])expect(src).not.toContain(needle);});
});