import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { loadAuthoringJson } from '../../src/ability/loader';
import { advanceAbilityPhase, calculateCardPower, dispatchAbilityCommand, initializeAbilityRuntime, playAbilityCardBatch, processAbilityEvent } from '../../src/ability/interpreter';
import { createSeededGameState } from '../../src/tools/seeded-state';
import type { GameState } from '../../src/schema/game';

const ROOT='master.amakusa';
const REL='amakusa.vassal';
const IDS=['master.amakusa.skill.ascension','master.amakusa.skill.s1','master.amakusa.skill.s1a','master.amakusa.skill.s2','master.amakusa.skill.s3'];
const PATH='data/authoring/masters/master.amakusa.json';
const raw=JSON.parse(readFileSync(PATH,'utf8'));
const loaded=loadAuthoringJson(raw);
const card=(id:string)=>loaded.cards[id]!;
const effectTypes=(id:string)=>card(id).abilities.flatMap(a=>a.effects.map(e=>e.type));
function add(state:GameState,definitionId:string,owner='p1',zone='skill',active=false,generatedBy?:string){const instanceId=`amakusa:${owner}:${definitionId}:${state.cards.length}`;state.cards.push({instanceId,definitionId,ownerPlayerId:owner,controllerPlayerId:owner,zone,visibility:['field','attack_area'].includes(zone)?{scope:'public'}:{scope:'owner_only',ownerPlayerId:owner},...(generatedBy?{generatedBy}:{})} as any);state.abilityRuntime!.cardState[instanceId]={active,faceDown:false,playedRound:state.round.roundNumber};return instanceId;}
function setSeals(state:GameState,id:string,value:number){(state.players.find(p=>p.id===id)! as any).commandSpells=value;}
function flag(state:GameState,id:string,field:string){return state.abilityRuntime!.structuredPlayerFlagsByPlayer?.[id]?.[`__fd_linked_role:${REL}:${field}`];}
function base(id:string,kind='phase_action'){return {id,kind,printedClause:id,activation:{phase:'action',opens:'controller_action_window'},conditions:[],targets:[],effects:[],cost:[],ruleModifiers:[],creates:[],lifecycle:{},responseWindow:{order:'turn_order',passBehavior:'decline_this_window'},limit:{},visibility:{},execution:{mode:'automatic',allowedOperations:[]}} as any;}
function compositeArchive(){
  const unlock=base('fixture.unlock'); unlock.effects=[{type:'unlock_controller_master_ascension'}];
  const member=base('fixture.member.action');
  const servant=(id:string,ownerId:string,abilities:any[],basePower=0,attrs:string[]=[])=>({id,name:id,cardType:'servant_skill',owner:{type:'servant',id:ownerId},cardFace:{typeLabel:'魔术',attributes:attrs,cost:0,basePower},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[],abilities,verification:{implementationStatus:'complete'}});
  const basic={id:'servant.fixture-amakusa.basic.one',name:'basic',cardType:'basic_attack',owner:{type:'servant',id:'servant.fixture-amakusa'},cardFace:{typeLabel:'基础',attributes:[],cost:0,basePower:2},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[],abilities:[],verification:{implementationStatus:'complete'}};
  return {...raw,cards:[...raw.cards,servant('servant.fixture-amakusa.skill.unlock','servant.fixture-amakusa',[unlock]),servant('servant.fixture-member.skill.s1','servant.fixture-member',[member],1),servant('servant.shakespeare.skill.sc-shakespeare-3','servant.shakespeare',[],1,['魔术','宝具']),basic]};
}
function setup(pack=loaded){const state=createSeededGameState({activeSeats:[1,2,3]});state.cards=[];state.players[0]!.masterCardId=ROOT;state.players[0]!.locationId='shinto';state.players[1]!.locationId='miyama_town';state.players[2]!.locationId='recon';state.players.forEach(p=>{p.mana=8;p.vp=0;});setSeals(state,'p1',3);setSeals(state,'p2',3);setSeals(state,'p3',1);initializeAbilityRuntime(state,pack,{seed:20261001});return state;}

describe('P3 Amakusa owner-complete migration',()=>{
  it('materializes exactly the complete frozen five-identity owner scope',()=>{expect(raw.id).toBe(ROOT);expect(raw.name).toBe('天草四郎');expect(raw.publicInformation.initialMana).toBe(4);expect(raw.cards.map((x:any)=>x.id).sort()).toEqual([...IDS].sort());expect(Object.keys(loaded.cards).sort()).toEqual([...IDS].sort());expect(loaded.report.filter(x=>x.status==='unsupported')).toEqual([]);});
  it('preserves frozen names/text and outside-game ascension metadata',()=>{expect(raw.cards.map((x:any)=>[x.id,x.name])).toEqual([['master.amakusa.skill.s1','教则'],['master.amakusa.skill.s1a','绝罚'],['master.amakusa.skill.s2','红队领袖'],['master.amakusa.skill.s3','神仆'],['master.amakusa.skill.ascension','过去的裁定者']]);expect(raw.cards.find((x:any)=>x.id==='master.amakusa.skill.ascension').initialPlacement).toBe('outside_game');expect(raw.cards.find((x:any)=>x.id==='master.amakusa.skill.ascension').printedText).toContain('开演之时已至，此处应有雷鸣般的喝彩');});
  it('consumes only the accepted Amakusa readiness capability families',()=>{expect(effectTypes('master.amakusa.skill.s1')).toEqual(['linked_role_initialize']);expect(effectTypes('master.amakusa.skill.s1a')).toEqual(['linked_role_copy_revealed_member_servant_skill']);expect(effectTypes('master.amakusa.skill.s2')).toEqual(['linked_role_schedule_member','linked_role_apply_scheduled_members']);expect(effectTypes('master.amakusa.skill.s3')).toEqual(['linked_role_member_rules','linked_role_battle_reward']);expect(effectTypes('master.amakusa.skill.ascension')).toEqual(['ascension_unlock_opponents_lose_command_seals','source_definition_basic_attack_power_bonus']);expect(card('master.amakusa.skill.ascension').abilities[1]!.activation.sourceDefinitionId).toBe('servant.shakespeare.skill.sc-shakespeare-3');});
  it('integrates Amakusa exactly once immediately after Alice',()=>{const pack=JSON.parse(readFileSync('data/packs/fd-playtest-v1/pack.json','utf8'));expect(pack.authoringMasterFiles.filter((x:string)=>x===PATH)).toHaveLength(1);expect(pack.authoringMasterFiles.slice(-2)).toEqual(['data/authoring/masters/master.alice.json',PATH]);});
  it('drives canonical Doctrine, vassalize and cross-battle reward through real definitions',()=>{const state=setup();const s1=add(state,'master.amakusa.skill.s1');const s2=add(state,'master.amakusa.skill.s2');add(state,'master.amakusa.skill.s3');processAbilityEvent(state,{id:'amakusa-game-start',type:'game_start',playerId:'p1'});expect(flag(state,'p1','leader')).toBe(true);expect(flag(state,'p2','memberLeader')).toBe('p1');expect(flag(state,'p2','ever')).toBe(true);state.round.activePhase='action';state.round.prioritySeat=state.players[0]!.seat;expect(dispatchAbilityCommand(state,'p1',{type:'activate_ability',cardInstanceId:s2,abilityId:'amakusa.s2.vassalize'}).ok).toBe(true);const d=state.abilityRuntime!.pendingDecision!;expect(d.candidates).toEqual(['p3']);expect(dispatchAbilityCommand(state,'p1',{type:'choose_target',decisionId:d.id,selectedIds:['p3']}).ok).toBe(true);expect((state.players[0] as any).commandSpells).toBe(1);advanceAbilityPhase(state,'round_start',2,1);expect(flag(state,'p3','memberLeader')).toBe('p1');processAbilityEvent(state,{id:'amakusa-battle',type:'after_battle_ended',battlePhaseResolutionId:'amakusa:1',battleParticipantIds:['p1','p2'],battleOutcomes:[{battlefieldId:'shinto',winnerPlayerIds:['p1']},{battlefieldId:'miyama_town',winnerPlayerIds:['p2']}]});expect(state.players[0]!.vp).toBe(1);expect(state.players[1]!.vp).toBe(1);expect(s1).toBeTruthy();});
  it('drives canonical Absolute Punishment copy, original lock and member removal',()=>{const pack=loadAuthoringJson(compositeArchive());for(const def of Object.values(pack.cards)){const d=def as any;if(d.id.startsWith('master.amakusa.'))d.ownerId=ROOT;else if(d.id.startsWith('servant.fixture-member.'))d.ownerId='servant.fixture-member';else if(d.id.startsWith('servant.fixture-amakusa.'))d.ownerId='servant.fixture-amakusa';else if(d.id.startsWith('servant.shakespeare.'))d.ownerId='servant.shakespeare';}const state=setup(pack);state.players[1]!.servantCardId='servant.fixture-member';state.abilityRuntime!.revealedServants.push('p2');add(state,'master.amakusa.skill.s1');add(state,'master.amakusa.skill.s3');const copySource=add(state,'master.amakusa.skill.s1a');const original=add(state,'servant.fixture-member.skill.s1','p2');processAbilityEvent(state,{id:'copy-game-start',type:'game_start',playerId:'p1'});state.round.activePhase='action';state.round.prioritySeat=state.players[0]!.seat;expect(dispatchAbilityCommand(state,'p1',{type:'activate_ability',cardInstanceId:copySource,abilityId:'amakusa.s1a.copy'}).ok).toBe(true);const d=state.abilityRuntime!.pendingDecision!;expect(d.candidates).toEqual([original]);expect(dispatchAbilityCommand(state,'p1',{type:'choose_target',decisionId:d.id,selectedIds:[original]}).ok).toBe(true);const copyId=Object.keys(state.abilityRuntime!.linkedRoleSkillCopies??{})[0]!;expect(dispatchAbilityCommand(state,'p1',{type:'play_card',cardInstanceId:copyId}).ok).toBe(true);expect(state.abilityRuntime!.linkedRoleOriginalSkillLocks?.[original]).toBe(state.round.roundNumber);expect(flag(state,'p2','memberLeader')).toBeUndefined();expect(flag(state,'p2','ever')).toBe(true);});
  it('drives canonical ascension seal loss and exact Shakespeare source-definition +4 Power',()=>{const pack=loadAuthoringJson(compositeArchive());for(const def of Object.values(pack.cards)){const d=def as any;if(d.id.startsWith('master.amakusa.'))d.ownerId=ROOT;else if(d.id.startsWith('servant.fixture-amakusa.'))d.ownerId='servant.fixture-amakusa';else if(d.id.startsWith('servant.shakespeare.'))d.ownerId='servant.shakespeare';}const state=setup(pack);state.players[0]!.servantCardId='servant.fixture-amakusa';const unlock=add(state,'servant.fixture-amakusa.skill.unlock');state.round.activePhase='action';state.round.prioritySeat=state.players[0]!.seat;expect(dispatchAbilityCommand(state,'p1',{type:'activate_ability',cardInstanceId:unlock,abilityId:'fixture.unlock'}).ok).toBe(true);const asc=state.cards.find(c=>c.definitionId==='master.amakusa.skill.ascension')!;expect(asc.generatedBy).toBe(unlock);expect((state.players[1] as any).commandSpells).toBe(1);expect((state.players[2] as any).commandSpells).toBe(0);const shakespeare=add(state,'servant.shakespeare.skill.sc-shakespeare-3','p1');const basic=add(state,'servant.fixture-amakusa.basic.one','p1','attack_area',true);expect(calculateCardPower(state,basic).value).toBe(2);playAbilityCardBatch(state,'p1',[{cardInstanceId:shakespeare}]);expect(calculateCardPower(state,basic).value).toBe(6);});
  it('adds no Amakusa/Shakespeare/card-name identity routing to production runtime',()=>{const files=['packages/rules/src/ability/linked-role-core-capability.ts','packages/rules/src/ability/linked-role-member-skill-copy-capability.ts','packages/rules/src/ability/master-ascension-event-power-capability.ts','packages/rules/src/ability/interpreter.ts','packages/rules/src/ability/loader.ts'];const production=files.map(f=>readFileSync(f,'utf8')).join('\n');for(const n of ['master.amakusa','天草四郎','红队领袖','神仆','过去的裁定者','servant.shakespeare','莎士比亚','开演之时已至','core.amakusa-'])expect(production).not.toContain(n);});
});