import { describe, expect, it } from 'vitest';
import { createSeededGameState } from '../../src/tools/seeded-state';
import { loadAuthoringJson } from '../../src/ability/loader';
import {
  calculateCardPower, dispatchAbilityCommand, effectiveCardPlayCost, executeAbility, initializeAbilityRuntime,
  isDeferredAbilityRuntimeProvenanceValidForRestore, playAbilityCardBatch, processAbilityEvent,
} from '../../src/ability/interpreter';
import { grantMana } from '../../src/core/rule-overrides';
import { playerCombatTotalPowerAdjustment } from '../../src/ability/owner-self-mechanics';
import { bloodlustValue, setBloodlustValue } from '../../src/ability/bloodlust-cycle-capability';
import type { GameState } from '../../src/schema/game';

const ROOT='master.fixture-bloodlust'; const RESOURCE='fixture.bloodlust';
const TRACK=`${ROOT}.tracker`, THRESH=`${ROOT}.threshold`, ASC=`${ROOT}.ascension`, PAY=`${ROOT}.pay-card`;
const INIT='fixture.bloodlust.init', CONTRIB='fixture.bloodlust.contrib', SPEND='fixture.bloodlust.spend', DECAY='fixture.bloodlust.decay';
const RULES='fixture.bloodlust.rules', ACTION='fixture.bloodlust.action', TRANSFORM='fixture.bloodlust.transform', ASCENSION='fixture.bloodlust.ascension', PAY_ABILITY='fixture.pay.ability';
function base(id:string,kind='passive'){return {id,kind,printedClause:id,activation:{},conditions:[],targets:[],effects:[],cost:[],ruleModifiers:[],creates:[],lifecycle:{},responseWindow:{order:'turn_order',passBehavior:'decline_this_window'},limit:{},visibility:{},execution:{mode:'automatic',allowedOperations:[]}} as any;}
function forced(id:string,trigger:string,effect:any){const a=base(id,'forced_trigger');a.activation={trigger};a.effects=[effect];return a;}
function marker(id:string,effect:any){const a=base(id);a.effects=[effect];return a;}
function action(id:string,effect:any){const a=base(id,'phase_action');a.activation={phase:'action',opens:'controller_action_window'};a.effects=[effect];return a;}
function archive(){
 const init=forced(INIT,'game_start',{type:'bloodlust_initialize',resourceKey:RESOURCE,initial:0});
 const contribution=marker(CONTRIB,{type:'bloodlust_same_battlefield_mana_contribution',resourceKey:RESOURCE,amountPerOpponentPerRound:1,minimumOpponentMana:6,requireSameBattlefield:true});
 const spend=marker(SPEND,{type:'bloodlust_track_controller_mana_spend',resourceKey:RESOURCE,gainPerManaSpent:1});
 const decay=forced(DECAY,'after_battle_ended',{type:'bloodlust_decay_after_battle',resourceKey:RESOURCE,minLoss:1,maxLoss:3,workshopMultiplier:2});
 const rules=marker(RULES,{type:'bloodlust_threshold_rules',resourceKey:RESOURCE,skillPowerThreshold:5,skillPowerBonus:1,playWaiverThreshold:10,playRequirementType:'skill_zone_mana_at_least',playRequirementValue:8,transformThreshold:15});
 const low=action(ACTION,{type:'bloodlust_low_threshold_action',resourceKey:RESOURCE,maximumResourceExclusive:5,manaGain:1,roundPowerGain:2,resourceGain:3,blockDecayThisRound:true});
 const transform=forced(TRANSFORM,'round_end',{type:'bloodlust_transform_at_round_end',resourceKey:RESOURCE,threshold:15,lockValue:15,removeAllCommandSeals:true,manaGainMultiplier:2,vpGainNumerator:1,vpGainDenominator:2,vpRounding:'floor'});
 const ascension=marker(ASCENSION,{type:'bloodlust_ascension_modifier_and_plunder',resourceKey:RESOURCE,transformedCostAdd:3,transformedPowerAdd:4,contributorPowerPenalty:-3});
 const pay=base(PAY_ABILITY,'phase_action');pay.activation={phase:'action',opens:'controller_action_window'};pay.cost=[{type:'pay_mana',amount:2}];pay.effects=[{type:'adjust_mana',amount:0}];
 const card=(id:string,abilities:any[],cost=0,power=0,requirements:any[]=[])=>({id,name:id,cardType:'master_skill',owner:{type:'master',id:ROOT},cardFace:{attributes:['特殊'],cost,basePower:power},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:requirements,abilities,verification:{implementationStatus:'complete'}});
 return {schemaVersion:'fd-card-authoring-v1',id:ROOT,cards:[card(TRACK,[init,contribution,spend,decay]),card(THRESH,[rules,low,transform,pay],2,4,[{type:'skill_zone_mana_at_least',value:8}]),card(ASC,[ascension],2,3),card(PAY,[],2,1)]} as any;
}
function add(state:GameState,definitionId:string,owner='p1',zone='skill',active=false){const instanceId=`${definitionId}:${owner}:${state.cards.length}`;state.cards.push({instanceId,definitionId,ownerPlayerId:owner,controllerPlayerId:owner,zone,visibility:['field','attack_area'].includes(zone)?{scope:'public'}:{scope:'owner_only',ownerPlayerId:owner}} as any);state.abilityRuntime!.cardState[instanceId]={active,faceDown:false,playedRound:state.round.roundNumber};return instanceId;}
function setup(){const pack=loadAuthoringJson(archive());expect(pack.report.filter(e=>e.status==='unsupported')).toEqual([]);const state=createSeededGameState({activeSeats:[1,2,3]});state.cards=[];initializeAbilityRuntime(state,pack,{seed:20261001});state.players.forEach(p=>{p.mana=10;p.vp=4;p.locationId='miyama_town';(p as any).commandSpells=3;});state.players[0]!.masterCardId=ROOT;state.round.activePhase='action';state.round.prioritySeat=state.players[0]!.seat;const ids={track:add(state,TRACK),threshold:add(state,THRESH),asc:add(state,ASC),pay:add(state,PAY)};processAbilityEvent(state,{id:'bloodlust-game-start',type:'game_start',playerId:'p1'});return {state,pack,ids};}
function activate(state:GameState,source:string,abilityId:string,extra:any={}){return dispatchAbilityCommand(state,'p1',{type:'activate_ability',cardInstanceId:source,abilityId,...extra});}

describe('P3 Akiha owner-readiness identity-free bloodlust-cycle capability',()=>{
 it('accepts exact shapes and fails closed when a privileged shape is widened',()=>{const good=loadAuthoringJson(archive());expect(good.report.filter(e=>e.status==='unsupported')).toEqual([]);const bad=archive();bad.cards[0].abilities[1].effects[0].minimumOpponentMana=5;const out=loadAuthoringJson(bad);expect(out.cards[TRACK]!.abilities[1]!.execution.mode).toBe('unsupported');expect(out.report.some(e=>e.reason.includes('Bloodlust'))).toBe(true);});
 it('tracks only actual controller mana spend as resource',()=>{const {state,ids}=setup();expect(bloodlustValue(state,'p1',RESOURCE)).toBe(0);playAbilityCardBatch(state,'p1',[{cardInstanceId:ids.pay}]);expect(state.players[0]!.mana).toBe(8);expect(bloodlustValue(state,'p1',RESOURCE)).toBe(2);});
 it('uses explicit same-battlefield >=6 opponent contribution atomically, once per opponent per round, and seals physical provenance',()=>{const {state,ids}=setup();state.players[0]!.mana=1;state.players[1]!.mana=6;playAbilityCardBatch(state,'p1',[{cardInstanceId:ids.pay,manaContributions:[{contributorPlayerId:'p2',amount:1}]}]);expect(state.players[0]!.mana).toBe(0);expect(state.players[1]!.mana).toBe(5);expect(bloodlustValue(state,'p1',RESOURCE)).toBe(1);expect(state.abilityRuntime!.cardState[ids.pay]!.playManaContributions).toEqual([{playerId:'p2',amount:1}]);const second=add(state,PAY,'p1','skill');state.players[0]!.mana=1;expect(()=>playAbilityCardBatch(state,'p1',[{cardInstanceId:second,manaContributions:[{contributorPlayerId:'p2',amount:1}]}])).toThrow();expect(state.players[0]!.mana).toBe(1);expect(state.players[1]!.mana).toBe(5);});
 it('supports the same explicit contribution transaction through the real ability command path',()=>{const {state,ids}=setup();state.players[0]!.mana=1;state.players[1]!.mana=6;const result=activate(state,ids.threshold,PAY_ABILITY,{manaContributions:[{contributorPlayerId:'p2',amount:1}]});expect(result.ok).toBe(true);expect(state.players[0]!.mana).toBe(0);expect(state.players[1]!.mana).toBe(5);expect(bloodlustValue(state,'p1',RESOURCE)).toBe(1);});
 it('rejects contribution from a different battlefield or contributor below six without partial payment',()=>{const {state,ids}=setup();state.players[0]!.mana=1;state.players[1]!.mana=5;expect(()=>playAbilityCardBatch(state,'p1',[{cardInstanceId:ids.pay,manaContributions:[{contributorPlayerId:'p2',amount:1}]}])).toThrow();expect(state.players[0]!.mana).toBe(1);expect(state.players[1]!.mana).toBe(5);state.players[1]!.mana=6;state.players[1]!.locationId='shinto';expect(()=>playAbilityCardBatch(state,'p1',[{cardInstanceId:ids.pay,manaContributions:[{contributorPlayerId:'p2',amount:1}]}])).toThrow();expect(state.players[1]!.mana).toBe(6);});
 it('decays 1-3 at battle end, doubles loss at workshop, and low action blocks decay this round',()=>{const normal=setup();setBloodlustValue(normal.state,'p1',RESOURCE,10);processAbilityEvent(normal.state,{id:'battle-end-normal',type:'after_battle_ended',battleParticipantIds:['p1','p2']});const loss=10-bloodlustValue(normal.state,'p1',RESOURCE);expect(loss).toBeGreaterThanOrEqual(1);expect(loss).toBeLessThanOrEqual(3);const workshop=setup();workshop.state.players[0]!.locationId='magic_workshop';setBloodlustValue(workshop.state,'p1',RESOURCE,10);processAbilityEvent(workshop.state,{id:'battle-end-workshop',type:'after_battle_ended',battleParticipantIds:['p1','p2']});const workshopLoss=10-bloodlustValue(workshop.state,'p1',RESOURCE);expect([2,4,6]).toContain(workshopLoss);const blocked=setup();const beforeMana=blocked.state.players[0]!.mana;expect(activate(blocked.state,blocked.ids.threshold,ACTION).ok).toBe(true);expect(blocked.state.players[0]!.mana).toBe(beforeMana+1);expect(bloodlustValue(blocked.state,'p1',RESOURCE)).toBe(3);processAbilityEvent(blocked.state,{id:'battle-end-blocked',type:'after_battle_ended',battleParticipantIds:['p1','p2']});expect(bloodlustValue(blocked.state,'p1',RESOURCE)).toBe(3);expect(playerCombatTotalPowerAdjustment(blocked.state,'p1')).toBe(2);});
 it('adds +1 skill Power at 5+ and waives only exact 8-mana skill-zone requirement at 10+',()=>{const {state,ids}=setup();const card=state.cards.find(c=>c.instanceId===ids.threshold)!;card.zone='attack_area';state.abilityRuntime!.cardState[ids.threshold]!.active=true;setBloodlustValue(state,'p1',RESOURCE,4);expect(calculateCardPower(state,ids.threshold).value).toBe(4);setBloodlustValue(state,'p1',RESOURCE,5);expect(calculateCardPower(state,ids.threshold).value).toBe(5);card.zone='skill';state.abilityRuntime!.cardState[ids.threshold]!.active=false;state.players[0]!.mana=7;setBloodlustValue(state,'p1',RESOURCE,9);expect(()=>playAbilityCardBatch(state,'p1',[{cardInstanceId:ids.threshold}])).toThrow();setBloodlustValue(state,'p1',RESOURCE,10);playAbilityCardBatch(state,'p1',[{cardInstanceId:ids.threshold}]);expect(state.players[0]!.mana).toBe(5);});
 it('transforms at 15 on round end, clears seals, locks resource, doubles mana gain, and halves positive VP gain floor',()=>{const {state}=setup();setBloodlustValue(state,'p1',RESOURCE,15);(state.players[0] as any).commandSpells=3;processAbilityEvent(state,{id:'transform-round-end',type:'round_end',playerId:'p1'});expect((state.players[0] as any).commandSpells).toBe(0);expect(bloodlustValue(state,'p1',RESOURCE)).toBe(15);state.players[0]!.mana=5;const mana=state.players[0]!.mana;grantMana(state,'p1',2,{source:'generic'});expect(state.players[0]!.mana).toBe(mana+4);state.players[0]!.vp+=5;processAbilityEvent(state,{id:'vp-reconcile',type:'round_start',playerId:'p1'});expect(state.players[0]!.vp).toBe(6);const card=add(state,PAY,'p1','skill');state.players[0]!.mana=20;playAbilityCardBatch(state,'p1',[{cardInstanceId:card}]);expect(bloodlustValue(state,'p1',RESOURCE)).toBe(15);});
 it('applies transformed ascension +3 cost/+4 Power but plunder only in untransformed state from real contribution provenance',()=>{const plain=setup();plain.state.players[0]!.mana=1;plain.state.players[1]!.mana=6;playAbilityCardBatch(plain.state,'p1',[{cardInstanceId:plain.ids.asc,manaContributions:[{contributorPlayerId:'p2',amount:1}]}]);expect(playerCombatTotalPowerAdjustment(plain.state,'p2')).toBe(-3);plain.state.abilityRuntime!.cardState[plain.ids.asc]!.active=false;expect(playerCombatTotalPowerAdjustment(plain.state,'p2')).toBe(0);const transformed=setup();setBloodlustValue(transformed.state,'p1',RESOURCE,15);processAbilityEvent(transformed.state,{id:'transform-asc',type:'round_end',playerId:'p1'});expect(effectiveCardPlayCost(transformed.state,'p1',transformed.ids.asc)).toBe(5);expect(calculateCardPower(transformed.state,transformed.ids.asc).value).toBe(7);});
 it('rejects forged provider, transform, and physical contribution restore provenance',()=>{const {state,ids}=setup();expect(isDeferredAbilityRuntimeProvenanceValidForRestore(state)).toBe(true);const provider=structuredClone(state);provider.abilityRuntime!.structuredPlayerFlagsByPlayer!.p1![`__fd_bloodlust:${RESOURCE}:providerSource`]='forged';expect(isDeferredAbilityRuntimeProvenanceValidForRestore(provider)).toBe(false);const transformed=structuredClone(state);setBloodlustValue(transformed,'p1',RESOURCE,15);processAbilityEvent(transformed,{id:'transform-forge',type:'round_end',playerId:'p1'});expect(isDeferredAbilityRuntimeProvenanceValidForRestore(transformed)).toBe(true);transformed.abilityRuntime!.structuredPlayerFlagsByPlayer!.p1![`__fd_bloodlust:${RESOURCE}:value`]=14;expect(isDeferredAbilityRuntimeProvenanceValidForRestore(transformed)).toBe(false);const contribution=structuredClone(state);contribution.abilityRuntime!.cardState[ids.pay]!.playManaContributions=[{playerId:'ghost',amount:1}];expect(isDeferredAbilityRuntimeProvenanceValidForRestore(contribution)).toBe(false);});
 it('keeps production capability source free of fixture/Akiha identities',()=>{const fs=require('node:fs');const src=fs.readFileSync('packages/rules/src/ability/bloodlust-cycle-capability.ts','utf8');for(const needle of ['master.akiha','远野秋叶','红赤朱','master.fixture-bloodlust','core.akiha-'])expect(src).not.toContain(needle);});
});
