import { describe, expect, it } from 'vitest';
import { createSeededGameState } from '../../src/tools/seeded-state';
import { loadAuthoringJson } from '../../src/ability/loader';
import { dispatchAbilityCommand, getLegalActions, initializeAbilityRuntime, isDeferredAbilityRuntimeProvenanceValidForRestore, processAbilityEvent } from '../../src/ability/interpreter';
import { effectiveLocationRestrictionBlocksMovement, effectiveLocationRestrictionRequiresFaceDownStandardAttack, isPlayerAtEffectiveLocationKind } from '../../src/ability/effective-location-restriction-capability';
import { movePlayer } from '../../src/core/movement';
import type { GameState } from '../../src/schema/game';

const ROOT='master.fixture-araya';
const TERRAIN_DEF=`${ROOT}.skill.terrain`, TERRAIN_ABILITY='fixture.terrain.increment';
const RESTRICT_DEF=`${ROOT}.skill.restrict`, RESTRICT_ABILITY='fixture.workshop.restrict';
function base(id:string,kind='passive'){return {id,kind,printedClause:id,activation:{},conditions:[],targets:[],effects:[],cost:[],ruleModifiers:[],creates:[],lifecycle:{},responseWindow:{order:'turn_order',passBehavior:'decline_this_window'},limit:{},visibility:{},execution:{mode:'automatic',allowedOperations:[]}} as any;}
function archive(providerDefinitionId=TERRAIN_DEF, providerAbilityId=TERRAIN_ABILITY){
  const terrain=base(TERRAIN_ABILITY,'forced_trigger');terrain.activation={trigger:'after_player_deployed_to_battlefield'};terrain.effects=[{type:'persistent_location_terrain_replace_increment',amount:1,max:5}];
  const restrict=base(RESTRICT_ABILITY);restrict.effects=[{type:'effective_location_same_location_restrictions',effectiveLocationKind:'workshop',persistentTerrainMinimum:5,persistentTerrainProviderDefinitionId:providerDefinitionId,persistentTerrainProviderAbilityId:providerAbilityId,blockOpponentExit:true,requireFaceDownStandardAttack:true}];
  const card=(id:string,abilities:any[])=>({id,name:id,cardType:'master_skill',owner:{type:'master',id:ROOT},cardFace:{typeLabel:'被动',attributes:[],cost:0,basePower:0},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[],abilities,verification:{implementationStatus:'complete'}});
  return {schemaVersion:'fd-card-authoring-v1',archiveType:'master_skill_card_archive',id:ROOT,name:'Fixture Araya',class:'Master',publicInformation:{type:'master_package',initialMana:4},cards:[card(TERRAIN_DEF,[terrain]),card(RESTRICT_DEF,[restrict])]} as any;
}
function add(state:GameState,definitionId:string,owner='p1',zone:any='skill'){const instanceId=`${owner}:${definitionId}:${state.cards.length}`;state.cards.push({instanceId,definitionId,ownerPlayerId:owner,controllerPlayerId:owner,zone,visibility:{scope:'owner_only',ownerPlayerId:owner}} as any);state.abilityRuntime!.cardState[instanceId]={active:false,faceDown:false,playedRound:state.round.roundNumber};return instanceId;}
function addBasic(state:GameState,id:string,owner='p2'){(state.abilityRuntime!.pack.cards as any)[id]={id,name:id,cardType:'basic_attack',ownerId:owner,cardFace:{typeLabel:'攻击',attributes:[],cost:0,basePower:1},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[],abilities:[],mode:'automatic'};return add(state,id,owner,'hand');}
function setup(providerDefinitionId=TERRAIN_DEF,providerAbilityId=TERRAIN_ABILITY){
  const pack=loadAuthoringJson(archive(providerDefinitionId,providerAbilityId)); expect(pack.report.filter(x=>x.status==='unsupported')).toEqual([]); for(const d of Object.values(pack.cards))(d as any).ownerId=ROOT;
  const state=createSeededGameState({activeSeats:[1,2,3]}); state.cards=[]; initializeAbilityRuntime(state,pack,{seed:20261001});
  state.players[0]!.locationId='shinto';state.players[1]!.locationId='shinto';state.players[2]!.locationId='miyama_town'; state.round.activePhase='action'; state.round.prioritySeat=state.players[1]!.seat;
  const terrainSource=add(state,TERRAIN_DEF,'p1'); const restrictionSource=add(state,RESTRICT_DEF,'p1');
  (state as any).modeState={terrainAssignments:{shinto:['p1','p2']},terrainAssignmentSlots:{shinto:{p1:0,p2:1}}};
  return {state,terrainSource,restrictionSource};
}
function buildFive(state:GameState){for(let i=1;i<=5;i++)processAbilityEvent(state,{id:`deploy:${i}`,type:'after_player_deployed_to_battlefield',playerId:'p1',locationId:'shinto'});}

describe('P3 Araya owner-readiness identity-free effective workshop restrictions',()=>{
  it('accepts only the exact privileged passive shape',()=>{const good=loadAuthoringJson(archive());expect(good.report.filter(x=>x.status==='unsupported')).toEqual([]);const bad=archive();(bad.cards[1].abilities[0].effects[0] as any).persistentTerrainMinimum=4;const out=loadAuthoringJson(bad);expect(out.cards[RESTRICT_DEF]!.abilities[0]!.execution.mode).toBe('unsupported');expect(out.report.some(x=>x.reason.includes('Effective-location restriction'))).toBe(true);});
  it('derives virtual workshop only for the controller at five bound terrain layers',()=>{const {state}=setup();buildFive(state);expect(isPlayerAtEffectiveLocationKind(state,'p1','workshop')).toBe(true);expect(isPlayerAtEffectiveLocationKind(state,'p2','workshop')).toBe(false);expect(effectiveLocationRestrictionBlocksMovement(state,'p2')).toBe(true);expect(effectiveLocationRestrictionRequiresFaceDownStandardAttack(state,'p2')).toBe(true);});
  it('requires the authored persistent-terrain provider definition and ability binding',()=>{const a=setup('master.other.skill.terrain',TERRAIN_ABILITY);buildFive(a.state);expect(isPlayerAtEffectiveLocationKind(a.state,'p1','workshop')).toBe(false);const b=setup(TERRAIN_DEF,'other.ability');buildFive(b.state);expect(isPlayerAtEffectiveLocationKind(b.state,'p1','workshop')).toBe(false);});
  it('blocks ordinary and effect movement while preserving the explicit trusted ignore exception',()=>{const {state}=setup();buildFive(state);state.round.prioritySeat=state.players[1]!.seat;const normal=movePlayer(state,{playerId:'p2',to:'recon',movementKind:'normal'});expect(normal.moved).toBe(false);expect(normal.reason).toBe('movement_locked');const effect=movePlayer(state,{playerId:'p2',to:'recon',movementKind:'effect'});expect(effect.moved).toBe(false);expect(effect.reason).toBe('movement_locked');const trusted=movePlayer(state,{playerId:'p2',to:'recon',movementKind:'effect',ignoreCardMovementRestrictions:true});expect(trusted.moved).toBe(true);});
  it('withholds staged-attack confirmation until at least one attack is face down',()=>{const {state}=setup();buildFive(state);const up=addBasic(state,'basic.fixture.up');const down=addBasic(state,'basic.fixture.down');expect(dispatchAbilityCommand(state,'p2',{type:'stage_attack_card',cardInstanceId:up}).ok).toBe(true);expect(getLegalActions(state,'p2').some(a=>a.type==='confirm_staged_attack')).toBe(false);const rejected=dispatchAbilityCommand(state,'p2',{type:'confirm_staged_attack'});expect(rejected.ok).toBe(false);expect(rejected.rejection?.code).toBe('play_requirement');expect(dispatchAbilityCommand(state,'p2',{type:'stage_attack_card',cardInstanceId:down,faceDown:true}).ok).toBe(true);expect(getLegalActions(state,'p2').some(a=>a.type==='confirm_staged_attack')).toBe(true);expect(dispatchAbilityCommand(state,'p2',{type:'confirm_staged_attack'}).ok).toBe(true);});
  it('source removal immediately disables virtual location, movement lock, and face-down requirement',()=>{const {state,restrictionSource}=setup();buildFive(state);state.cards.find(c=>c.instanceId===restrictionSource)!.zone='discard';expect(isPlayerAtEffectiveLocationKind(state,'p1','workshop')).toBe(false);expect(effectiveLocationRestrictionBlocksMovement(state,'p2')).toBe(false);expect(effectiveLocationRestrictionRequiresFaceDownStandardAttack(state,'p2')).toBe(false);});
  it('applies same-location restrictions when the controller is physically at magic_workshop without virtual terrain',()=>{const {state}=setup();state.players[0]!.locationId='magic_workshop';state.players[1]!.locationId='magic_workshop';expect(isPlayerAtEffectiveLocationKind(state,'p1','workshop')).toBe(true);expect(isPlayerAtEffectiveLocationKind(state,'p2','workshop')).toBe(true);expect(effectiveLocationRestrictionBlocksMovement(state,'p2')).toBe(true);expect(effectiveLocationRestrictionRequiresFaceDownStandardAttack(state,'p2')).toBe(true);});
  it('fails restore on a forged live restriction-source controller but allows a legitimately removed source',()=>{const {state,restrictionSource}=setup();buildFive(state);expect(isDeferredAbilityRuntimeProvenanceValidForRestore(state)).toBe(true);const forged=structuredClone(state);forged.cards.find(c=>c.instanceId===restrictionSource)!.controllerPlayerId='p2';expect(isDeferredAbilityRuntimeProvenanceValidForRestore(forged)).toBe(false);const removed=structuredClone(state);removed.cards.find(c=>c.instanceId===restrictionSource)!.zone='discard';expect(isDeferredAbilityRuntimeProvenanceValidForRestore(removed)).toBe(true);});
});