import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import { createSeededGameState } from '../../src/tools/seeded-state';
import { loadAuthoringJson } from '../../src/ability/loader';
import { dispatchAbilityCommand, initializeAbilityRuntime, isCanonicalGenericPendingDecisionForRestore, processAbilityEvent } from '../../src/ability/interpreter';
import type { GameState } from '../../src/schema/game';

const ROOT='master.fixture-origin-stillness', CARD=ROOT+'.skill.s1a', ABILITY='fixture.origin-stillness';
function archive(multiplier=2){return {schemaVersion:'fd-card-authoring-v1',archiveType:'master_skill_card_archive',id:ROOT,name:'Fixture Origin Stillness',class:'Master',publicInformation:{type:'master_package',initialMana:4},cards:[{id:CARD,name:'Origin Stillness',cardType:'master_skill',owner:{type:'master',id:ROOT},printedText:'fixture',cardFace:{typeLabel:'被动',attributes:[],cost:0,basePower:0},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[],abilities:[{id:ABILITY,kind:'forced_trigger',printedClause:'fixture',activation:{trigger:'after_battle_ended'},conditions:[],targets:[{id:'active_basic_attack',type:'card_instance',scope:{zone:'attack_area',owner:'controller',controller:'self'},count:{min:1,max:1},constraints:[]}],effects:[{type:'recycle_active_basic_for_printed_cost_mana',target:'active_basic_attack',printedCostMultiplier:multiplier}],cost:[],ruleModifiers:[],creates:[],lifecycle:{},responseWindow:{order:'turn_order',passBehavior:'decline_this_window'},limit:{},visibility:{},execution:{mode:'automatic',allowedOperations:[]}}],verification:{implementationStatus:'complete'}}]} as any;}
function add(state:GameState,definitionId:string,zone='skill',owner='p1',active=false,faceDown=false){const id=owner+':'+definitionId+':'+state.cards.length;state.cards.push({instanceId:id,definitionId,ownerPlayerId:owner,controllerPlayerId:owner,zone,visibility:{scope:'owner_only',ownerPlayerId:owner}} as any);state.abilityRuntime!.cardState[id]={active,faceDown,playedRound:state.round.roundNumber};return id;}
function setup(){const pack=loadAuthoringJson(archive());expect(pack.report.filter(x=>x.status==='unsupported')).toEqual([]);(pack.cards[CARD] as any).ownerId=ROOT;(pack.cards as any)['fixture.basic.cost3']={id:'fixture.basic.cost3',name:'b3',cardType:'basic_attack',ownerId:'servant.fixture',ownerType:'servant',cardFace:{typeLabel:'基础',attributes:[],cost:3,basePower:2},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[],abilities:[],mode:'automatic'};(pack.cards as any)['fixture.basic.cost1']={id:'fixture.basic.cost1',name:'b1',cardType:'basic_attack',ownerId:'servant.fixture',ownerType:'servant',cardFace:{typeLabel:'基础',attributes:[],cost:1,basePower:2},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[],abilities:[],mode:'automatic'};(pack.cards as any)['fixture.nonbasic']={id:'fixture.nonbasic',name:'n',cardType:'servant_attack',ownerId:'servant.fixture',ownerType:'servant',cardFace:{typeLabel:'攻击',attributes:[],cost:5,basePower:5},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[],abilities:[],mode:'automatic'};const state=createSeededGameState({activeSeats:[1,2]});state.cards=[];initializeAbilityRuntime(state,pack,{seed:20261001});state.players[0]!.mana=1;const source=add(state,CARD);const good=add(state,'fixture.basic.cost3','attack_area','p1',true,false);const other=add(state,'fixture.basic.cost1','attack_area','p1',true,false);const faceDown=add(state,'fixture.basic.cost1','attack_area','p1',true,true);const nonbasic=add(state,'fixture.nonbasic','attack_area','p1',true,false);const opponent=add(state,'fixture.basic.cost1','attack_area','p2',true,false);state.abilityRuntime!.cardState[good]!.paidManaOnPlay=0;return {state,source,good,other,faceDown,nonbasic,opponent};}
function terminal(){return {id:'battle-phase:1:after_battle_ended',type:'after_battle_ended' as const,battlePhaseResolutionId:'battle-phase:1',battleParticipantIds:['p1','p2']};}

describe('P3 Araya owner-readiness origin stillness printed-cost authority',()=>{
 it('accepts only exact x2 privileged shape',()=>{expect(loadAuthoringJson(archive()).report.filter(x=>x.status==='unsupported')).toEqual([]);const bad=loadAuthoringJson(archive(3));expect(bad.cards[CARD]!.abilities[0]!.execution.mode).toBe('unsupported');});
 it('offers only controller active face-up basic attacks',()=>{const {state,good,other}=setup();processAbilityEvent(state,terminal());const d=state.abilityRuntime!.pendingDecision!;expect(d.candidates.sort()).toEqual([good,other].sort());});
 it('recycles the exact selected physical and gains printed cost x2 rather than paid mana',()=>{const {state,good}=setup();processAbilityEvent(state,terminal());const d=state.abilityRuntime!.pendingDecision!;const before=state.players[0]!.mana;expect(dispatchAbilityCommand(state,'p1',{type:'choose_target',decisionId:d.id,selectedIds:[good]}).ok).toBe(true);expect(state.cards.find(c=>c.instanceId===good)!.zone).toBe('deck');expect(state.players[0]!.mana).toBe(before+6);});
 it('fails closed when the chosen physical loses active-basic provenance before resolution',()=>{const {state,good}=setup();processAbilityEvent(state,terminal());const d=state.abilityRuntime!.pendingDecision!;state.abilityRuntime!.cardState[good]!.active=false;expect(dispatchAbilityCommand(state,'p1',{type:'choose_target',decisionId:d.id,selectedIds:[good]}).ok).toBe(false);});
 it('rejects forged pending-decision candidate provenance on restore',()=>{const {state}=setup();processAbilityEvent(state,terminal());expect(isCanonicalGenericPendingDecisionForRestore(state,state.abilityRuntime!.pendingDecision!)).toBe(true);const forged=structuredClone(state);forged.abilityRuntime!.pendingDecision!.candidates=['forged'];expect(isCanonicalGenericPendingDecisionForRestore(forged,forged.abilityRuntime!.pendingDecision!)).toBe(false);});
 it('keeps production capability identity-free',()=>{const src=fs.readFileSync('packages/rules/src/ability/origin-stillness-printed-cost-capability.ts','utf8');for(const needle of ['master.araya','荒耶宗莲','起源：静止','core.araya-'])expect(src).not.toContain(needle);});
});
