import { describe, expect, it } from 'vitest';
import { createSeededGameState } from '../../src/tools/seeded-state';
import { loadAuthoringJson } from '../../src/ability/loader';
import { advanceAbilityPhase, dispatchAbilityCommand, initializeAbilityRuntime, isDeferredAbilityRuntimeProvenanceValidForRestore, playAbilityCardBatch, processAbilityEvent } from '../../src/ability/interpreter';
import { linkedRoleEntrySealAuthority, removeLinkedRoleMember } from '../../src/ability/linked-role-core-capability';
import { movePlayer } from '../../src/core/movement';
import type { GameState } from '../../src/schema/game';

const ROOT='master.fixture-linked-role', REL='fixture.covenant';
const S1=`${ROOT}.skill.s1`, S2=`${ROOT}.skill.s2`, S3=`${ROOT}.skill.s3`, PAY=`${ROOT}.skill.pay`, PLAY=`${ROOT}.skill.play`;
const INIT='fixture.link.init', SCHEDULE='fixture.link.schedule', APPLY='fixture.link.apply', RULES='fixture.link.rules', REWARD='fixture.link.reward', PAY_ABILITY='fixture.link.pay';
const LEADER='fixture.leader', MEMBER='fixture.member';
function base(id:string,kind='passive'){return {id,kind,printedClause:id,activation:{},conditions:[],targets:[],effects:[],cost:[],ruleModifiers:[],creates:[],lifecycle:{},responseWindow:{order:'turn_order',passBehavior:'decline_this_window'},limit:{},visibility:{},execution:{mode:'automatic',allowedOperations:[]}} as any;}
function archive(){
 const init=base(INIT,'forced_trigger');init.activation={trigger:'game_start'};init.effects=[{type:'linked_role_initialize',relationshipKey:REL,leaderRoleKey:LEADER,memberRoleKey:MEMBER,memberSelector:'next_seat'}];
 const schedule=base(SCHEDULE,'phase_action');schedule.activation={phase:'action',opens:'controller_action_window'};schedule.targets=[{id:'member',type:'player',count:{min:1,max:1},constraints:[]}];schedule.effects=[{type:'linked_role_schedule_member',relationshipKey:REL,leaderRoleKey:LEADER,memberRoleKey:MEMBER,target:'member',baseCommandSealCost:1,perActiveMemberCommandSealCost:1,activateAt:'next_round_start',requireNeverMember:true,requireFewerSealsBeforeSpend:true}];
 const apply=base(APPLY,'forced_trigger');apply.activation={trigger:'round_start'};apply.effects=[{type:'linked_role_apply_scheduled_members',relationshipKey:REL,leaderRoleKey:LEADER,memberRoleKey:MEMBER}];
 const rules=base(RULES);rules.effects=[{type:'linked_role_member_rules',relationshipKey:REL,leaderRoleKey:LEADER,memberRoleKey:MEMBER,entryCommandSealCost:1,entryOnlyBeforeClimax:true,manaContributionAmount:1,manaContributionMaxPerRound:1,requireDifferentBattlefields:true}];
 const reward=base(REWARD,'forced_trigger');reward.activation={trigger:'after_battle_ended'};reward.effects=[{type:'linked_role_battle_reward',relationshipKey:REL,leaderRoleKey:LEADER,memberRoleKey:MEMBER,vpEach:1,requireDifferentBattlefields:true}];
 const pay=base(PAY_ABILITY,'phase_action');pay.activation={phase:'action',opens:'controller_action_window'};pay.cost=[{type:'pay_mana',amount:2}];
 const card=(id:string,abilities:any[],cost=0)=>({id,name:id,cardType:'master_skill',owner:{type:'master',id:ROOT},cardFace:{typeLabel:'被动',attributes:[],cost,basePower:0},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:[],abilities,verification:{implementationStatus:'complete'}});
 return {schemaVersion:'fd-card-authoring-v1',archiveType:'master_skill_card_archive',id:ROOT,name:'Fixture Linked Role',class:'Master',publicInformation:{type:'master_package',initialMana:4},cards:[card(S1,[init]),card(S2,[schedule,apply]),card(S3,[rules,reward]),card(PAY,[pay]),card(PLAY,[],2)]} as any;
}
function add(state:GameState,definitionId:string,owner='p1'){const instanceId=`${owner}:${definitionId}:${state.cards.length}`;state.cards.push({instanceId,definitionId,ownerPlayerId:owner,controllerPlayerId:owner,zone:'skill',visibility:{scope:'owner_only',ownerPlayerId:owner}} as any);state.abilityRuntime!.cardState[instanceId]={active:false,faceDown:false,playedRound:state.round.roundNumber};return instanceId;}
function setSeals(state:GameState,id:string,value:number){(state.players.find(p=>p.id===id)! as any).commandSpells=value;}
function seals(state:GameState,id:string){return Number((state.players.find(p=>p.id===id)! as any).commandSpells??3);}
function setup(){const pack=loadAuthoringJson(archive());expect(pack.report.filter(x=>x.status==='unsupported')).toEqual([]);for(const def of Object.values(pack.cards))(def as any).ownerId=ROOT;const state=createSeededGameState({activeSeats:[1,2,3]});state.cards=[];initializeAbilityRuntime(state,pack,{seed:20261001});state.players[0]!.locationId='shinto';state.players[1]!.locationId='miyama_town';state.players[2]!.locationId='recon';state.players.forEach(p=>{p.mana=5;p.vp=0;});setSeals(state,'p1',3);setSeals(state,'p2',3);setSeals(state,'p3',1);const ids={s1:add(state,S1,'p1'),s2:add(state,S2,'p1'),s3:add(state,S3,'p1'),pay:add(state,PAY,'p2'),play:add(state,PLAY,'p2')};processAbilityEvent(state,{id:'fixture-game-start',type:'game_start',playerId:'p1'});return {state,pack,ids};}
function flag(state:GameState,id:string,field:string){return state.abilityRuntime!.structuredPlayerFlagsByPlayer?.[id]?.[`__fd_linked_role:${REL}:${field}`];}

describe('P3 Amakusa owner-readiness identity-free linked-role core',()=>{
 it('accepts exact privileged shapes and rejects widening',()=>{const good=loadAuthoringJson(archive());expect(good.report.filter(x=>x.status==='unsupported')).toEqual([]);const bad=archive();(bad.cards[0].abilities[0].effects[0] as any).extra=true;const out=loadAuthoringJson(bad);expect(out.cards[S1]!.abilities[0]!.execution.mode).toBe('unsupported');expect(out.report.some(x=>x.reason.includes('Linked-role'))).toBe(true);});
 it('initializes one leader plus next-seat member with permanent ever history',()=>{const {state}=setup();expect(flag(state,'p1','leader')).toBe(true);expect(flag(state,'p1','leaderRole')).toBe(LEADER);expect(flag(state,'p2','memberLeader')).toBe('p1');expect(flag(state,'p2','memberRole')).toBe(MEMBER);expect(flag(state,'p2','ever')).toBe(true);expect(flag(state,'p2','lastLeader')).toBe('p1');});
 it('spends dynamic seals, schedules a never-member target, applies next round, and never clears ever history',()=>{const {state,ids}=setup();state.round.activePhase='action';state.round.prioritySeat=state.players[0]!.seat;const start=dispatchAbilityCommand(state,'p1',{type:'activate_ability',cardInstanceId:ids.s2,abilityId:SCHEDULE});expect(start.ok).toBe(true);const d=state.abilityRuntime!.pendingDecision!;expect(d.candidates).toEqual(['p3']);const done=dispatchAbilityCommand(state,'p1',{type:'choose_target',decisionId:d.id,selectedIds:['p3']});expect(done.ok).toBe(true);expect(seals(state,'p1')).toBe(1);expect(flag(state,'p3','memberLeader')).toBeUndefined();expect(flag(state,'p3','pendingRound')).toBe(2);advanceAbilityPhase(state,'round_start',2,1);expect(flag(state,'p3','memberLeader')).toBe('p1');expect(flag(state,'p3','ever')).toBe(true);expect(removeLinkedRoleMember(state,'p1','p3',REL)).toBe(true);expect(flag(state,'p3','memberLeader')).toBeUndefined();expect(flag(state,'p3','ever')).toBe(true);state.round.activePhase='action';state.round.prioritySeat=state.players[0]!.seat;setSeals(state,'p1',3);expect(dispatchAbilityCommand(state,'p1',{type:'activate_ability',cardInstanceId:ids.s2,abilityId:SCHEDULE}).ok).toBe(false);});
 it('charges one entry seal and one linked mana on a real normal movement transaction while preserving input state',()=>{const {state}=setup();state.round.activePhase='action';state.players[1]!.mana=1;state.players[0]!.mana=5;const before=structuredClone(state);const moved=movePlayer(state,{playerId:'p2',to:'shinto',movementKind:'normal',manaContributions:[{contributorPlayerId:'p1',amount:1}]});expect(moved.moved).toBe(true);expect(moved.manaSpent).toBe(2);expect(moved.nextState.players[1]!.locationId).toBe('shinto');expect(moved.nextState.players[1]!.mana).toBe(0);expect(moved.nextState.players[0]!.mana).toBe(4);expect(seals(moved.nextState,'p2')).toBe(2);expect(state.players[1]!.locationId).toBe(before.players[1]!.locationId);expect(state.players[1]!.mana).toBe(before.players[1]!.mana);expect(state.players[0]!.mana).toBe(before.players[0]!.mana);});
 it('blocks unaffordable pre-climax entry, but climax/effect entry does not pay the linked seal tax',()=>{const a=setup();a.state.round.activePhase='action';setSeals(a.state,'p2',0);a.state.players[1]!.mana=5;const blocked=movePlayer(a.state,{playerId:'p2',to:'shinto',movementKind:'normal'});expect(blocked.moved).toBe(false);expect(blocked.reason).toBe('insufficient_command_seals');const climax=setup();climax.state.round.activePhase='action';climax.state.round.roundNumber=9;setSeals(climax.state,'p2',0);climax.state.players[1]!.mana=5;const allowed=movePlayer(climax.state,{playerId:'p2',to:'shinto',movementKind:'normal'});expect(allowed.moved).toBe(true);expect(seals(allowed.nextState,'p2')).toBe(0);const effect=setup();setSeals(effect.state,'p2',0);const forced=movePlayer(effect.state,{playerId:'p2',to:'shinto',movementKind:'effect'});expect(forced.moved).toBe(true);expect(seals(forced.nextState,'p2')).toBe(0);});
 it('uses the leader one mana once per round through the real ability payment path',()=>{const {state,ids}=setup();state.round.activePhase='action';state.round.prioritySeat=state.players[1]!.seat;state.players[1]!.mana=1;state.players[0]!.mana=5;const paid=dispatchAbilityCommand(state,'p2',{type:'activate_ability',cardInstanceId:ids.pay,abilityId:PAY_ABILITY,manaContributions:[{contributorPlayerId:'p1',amount:1}]});expect(paid.ok).toBe(true);expect(state.players[1]!.mana).toBe(0);expect(state.players[0]!.mana).toBe(4);const second=add(state,PAY,'p2');state.players[1]!.mana=1;expect(dispatchAbilityCommand(state,'p2',{type:'activate_ability',cardInstanceId:second,abilityId:PAY_ABILITY,manaContributions:[{contributorPlayerId:'p1',amount:1}]}).ok).toBe(false);});
 it('keeps linked-role card payment out of Bloodlust physical contribution provenance',()=>{const {state,ids}=setup();state.round.activePhase='action';state.round.prioritySeat=state.players[1]!.seat;state.players[1]!.mana=1;state.players[0]!.mana=5;playAbilityCardBatch(state,'p2',[{cardInstanceId:ids.play,manaContributions:[{contributorPlayerId:'p1',amount:1}]}]);expect(state.players[1]!.mana).toBe(0);expect(state.players[0]!.mana).toBe(4);expect(state.abilityRuntime!.cardState[ids.play]!.playManaContributions).toBeUndefined();});
 it('rewards leader and member once when they win different battlefields in one authoritative terminal',()=>{const {state}=setup();processAbilityEvent(state,{id:'terminal-one',type:'after_battle_ended',battlePhaseResolutionId:'phase:1',battleParticipantIds:['p1','p2'],battleOutcomes:[{battlefieldId:'shinto',winnerPlayerIds:['p1']},{battlefieldId:'miyama_town',winnerPlayerIds:['p2']}]});expect(state.players[0]!.vp).toBe(1);expect(state.players[1]!.vp).toBe(1);processAbilityEvent(state,{id:'terminal-two',type:'after_battle_ended',battlePhaseResolutionId:'phase:1b',battleParticipantIds:['p1','p2'],battleOutcomes:[{battlefieldId:'shinto',winnerPlayerIds:['p1']},{battlefieldId:'miyama_town',winnerPlayerIds:['p2']}]});expect(state.players[0]!.vp).toBe(1);expect(state.players[1]!.vp).toBe(1);const same=setup();processAbilityEvent(same.state,{id:'terminal-same',type:'after_battle_ended',battlePhaseResolutionId:'phase:2',battleParticipantIds:['p1','p2'],battleOutcomes:[{battlefieldId:'shinto',winnerPlayerIds:['p1','p2']}]});expect(same.state.players[0]!.vp).toBe(0);expect(same.state.players[1]!.vp).toBe(0);});
 it('rejects forged linked-role restore flags and missing provider provenance without identity routing',()=>{const {state,ids}=setup();expect(isDeferredAbilityRuntimeProvenanceValidForRestore(state)).toBe(true);const forged=structuredClone(state);(forged.abilityRuntime!.structuredPlayerFlagsByPlayer!.p3??={})[`__fd_linked_role:${REL}:memberLeader`]='p1';expect(isDeferredAbilityRuntimeProvenanceValidForRestore(forged)).toBe(false);const missing=structuredClone(state);missing.cards.find(c=>c.instanceId===ids.s3)!.zone='discard';expect(isDeferredAbilityRuntimeProvenanceValidForRestore(missing)).toBe(false);const fs=require('node:fs');const src=fs.readFileSync('packages/rules/src/ability/linked-role-core-capability.ts','utf8');for(const needle of ['master.amakusa','天草四郎','神仆','红队领袖','过去的裁定者','core.amakusa-'])expect(src).not.toContain(needle);});
 it('exposes the same pre-climax entry authority for deployment commit paths',()=>{const {state}=setup();state.players[1]!.locationId=undefined;const auth=linkedRoleEntrySealAuthority(state,'p2','shinto');expect(auth?.cost).toBe(1);expect(auth?.leaderId).toBe('p1');});
});