import { describe, expect, it } from 'vitest';
import { createSeededGameState } from '../../src/tools/seeded-state';
import { loadAuthoringJson } from '../../src/ability/loader';
import { initializeAbilityRuntime, processAbilityEvent, dispatchAbilityCommand } from '../../src/ability/interpreter';
import type { AbilityDefinitionPack } from '../../src/ability/types';

const MASTER='master.fixture-owner';
const SERVANT='servant.fixture-poet';
const SOURCE=`${SERVANT}.skill.unlock`;
const ASC=`${MASTER}.skill.ascension`;
const EFFECT='unlock_controller_master_ascension';
function ability(kind:'forced_trigger'|'phase_action'='forced_trigger') { return {id:'fixture.unlock',kind,printedClause:'fixture unlock',activation:kind==='forced_trigger'?{trigger:'round_start'}:{phase:'action',opens:'controller_action_window'},conditions:[],targets:[],effects:[{type:EFFECT}],cost:[],ruleModifiers:[],creates:[],lifecycle:{},responseWindow:{},limit:{},visibility:{},execution:{mode:'automatic',allowedOperations:[]}}; }
function card(id:string,ownerType:'master'|'servant',ownerId:string,abilities:any[],outside=false){return {id,name:id,cardType:ownerType==='master'?'master_skill':'servant_skill',owner:{type:ownerType,id:ownerId},printedText:id,cardFace:{typeLabel:outside?'魔术':'被动',attributes:[],cost:outside?3:0,basePower:outside?6:0},playTiming:{phase:'action',window:'controller_play_card_window'},playRequirements:outside?[{type:'skill_zone_mana_at_least',value:3}]:[],abilities,...(outside?{initialPlacement:'outside_game'}:{}),verification:{implementationStatus:'complete'}};}
function servantArchive(a=ability()){return {schemaVersion:'fd-card-authoring-v1',archiveType:'servant_skill_card_archive',id:SERVANT,name:'Fixture Poet',class:'Caster',cards:[card(SOURCE,'servant',SERVANT,[a])]} as any;}
function masterArchive(){return {schemaVersion:'fd-card-authoring-v1',archiveType:'master_skill_card_archive',id:MASTER,name:'Fixture Owner',class:'Master',publicInformation:{type:'master_package',initialMana:4},cards:[card(ASC,'master',MASTER,[],true)]} as any;}
function setup(a=ability()){const sp=loadAuthoringJson(servantArchive(a));const mp=loadAuthoringJson(masterArchive());expect(sp.report.filter(x=>x.status==='unsupported')).toEqual([]);expect(mp.report.filter(x=>x.status==='unsupported')).toEqual([]);(sp.cards[SOURCE] as any).ownerId=SERVANT;(mp.cards[ASC] as any).ownerId=MASTER;const pack:AbilityDefinitionPack={cards:{...sp.cards,...mp.cards}};const state=createSeededGameState({activeSeats:[1,2,3]});state.cards=[];state.players[0]!.masterCardId=MASTER;state.players[0]!.servantCardId=SERVANT;initializeAbilityRuntime(state,pack,{seed:20261001});const instanceId='fixture-unlock-source';state.cards.push({instanceId,definitionId:SOURCE,ownerPlayerId:'p1',controllerPlayerId:'p1',zone:'skill',visibility:{scope:'owner_only',ownerPlayerId:'p1'}});state.abilityRuntime!.cardState[instanceId]={active:false,faceDown:false,playedRound:state.round.roundNumber};return {state,instanceId};}

describe('P3 generic master-ascension unlock readiness',()=>{
  it('unlocks the current master ascension through the real round_start trigger exactly once',()=>{const {state,instanceId}=setup();processAbilityEvent(state,{id:'unlock-round-1',type:'round_start'});const created=state.cards.filter(c=>c.definitionId===ASC);expect(created).toHaveLength(1);expect(created[0]).toMatchObject({ownerPlayerId:'p1',controllerPlayerId:'p1',zone:'skill',generatedBy:instanceId});expect(state.abilityRuntime!.cardState[created[0]!.instanceId]).toMatchObject({active:false,faceDown:false});processAbilityEvent(state,{id:'unlock-round-2',type:'round_start'});expect(state.cards.filter(c=>c.definitionId===ASC)).toHaveLength(1);});
  it('does not activate a stale source after the controller servant changes',()=>{const {state}=setup();state.players[0]!.servantCardId='servant.fixture-other';processAbilityEvent(state,{id:'stale-round',type:'round_start'});expect(state.cards.some(c=>c.definitionId===ASC)).toBe(false);});
  it('supports the same exact generic semantic as an action activation',()=>{const a=ability('phase_action');const {state,instanceId}=setup(a);state.round.activePhase='action';state.round.prioritySeat=state.players[0]!.seat;const result=dispatchAbilityCommand(state,'p1',{type:'activate_ability',cardInstanceId:instanceId,abilityId:'fixture.unlock'});expect(result.ok).toBe(true);expect(state.cards.filter(c=>c.definitionId===ASC)).toHaveLength(1);});
  it('fails loader admission when the privileged effect shape is widened',()=>{const a=ability() as any;a.effects[0].targetDefinitionId=ASC;const pack=loadAuthoringJson(servantArchive(a));expect(pack.report.some(x=>x.path.includes('masterAscensionUnlock.gateway'))).toBe(true);});
  it('keeps production implementation free of fixture and owner identities',()=>{const fs=require('node:fs');const src=fs.readFileSync('packages/rules/src/ability/master-ascension-unlock-capability.ts','utf8');for(const needle of ['master.akiha','servant.shakespeare','远野秋叶','莎士比亚','master.fixture-owner','servant.fixture-poet'])expect(src).not.toContain(needle);});
});