import type { GameState } from '../schema/game';
import type { AbilityEvent, AuthoringAbility, EffectContext, ManaContributionChoice, RuleNode } from './types';
import { bloodlustVpGainAdjustment } from './bloodlust-cycle-capability';

export const LINKED_ROLE_INITIALIZE_EFFECT = 'linked_role_initialize' as const;
export const LINKED_ROLE_SCHEDULE_MEMBER_EFFECT = 'linked_role_schedule_member' as const;
export const LINKED_ROLE_APPLY_SCHEDULED_EFFECT = 'linked_role_apply_scheduled_members' as const;
export const LINKED_ROLE_MEMBER_RULES_EFFECT = 'linked_role_member_rules' as const;
export const LINKED_ROLE_BATTLE_REWARD_EFFECT = 'linked_role_battle_reward' as const;

const privileged = new Set<string>([LINKED_ROLE_INITIALIZE_EFFECT,LINKED_ROLE_SCHEDULE_MEMBER_EFFECT,LINKED_ROLE_APPLY_SCHEDULED_EFFECT,LINKED_ROLE_MEMBER_RULES_EFFECT,LINKED_ROLE_BATTLE_REWARD_EFFECT]);
const PREFIX='__fd_linked_role:';
function rec(v:unknown):v is Record<string,unknown>{return !!v&&typeof v==='object'&&!Array.isArray(v);}
function exact(v:unknown,keys:readonly string[]):boolean{if(!rec(v))return false;const a=Object.keys(v);return a.length===keys.length&&a.every(k=>keys.includes(k));}
function key(v:unknown):v is string{return typeof v==='string'&&/^[a-z0-9][a-z0-9:._-]{0,95}$/i.test(v);}
function empty(v:unknown):boolean{return rec(v)&&Object.keys(v).length===0;}
function standardResponse(a:AuthoringAbility):boolean{const ks=Object.keys(a.responseWindow);return ks.every(k=>['order','passBehavior'].includes(k))&&(a.responseWindow.order===undefined||a.responseWindow.order==='turn_order')&&(a.responseWindow.passBehavior===undefined||a.responseWindow.passBehavior==='decline_this_window');}
function common(a:AuthoringAbility):boolean{return a.cost.length===0&&a.creates.length===0&&a.ruleModifiers.length===0&&empty(a.lifecycle)&&empty(a.limit)&&empty(a.visibility)&&standardResponse(a)&&a.execution.mode==='automatic'&&Array.isArray(a.execution.allowedOperations)&&a.execution.allowedOperations.length===0;}
function relationship(e:RuleNode):string|undefined{return key(e.relationshipKey)?String(e.relationshipKey):undefined;}
function roleKeys(e:RuleNode):boolean{return key(e.leaderRoleKey)&&key(e.memberRoleKey);}
function initEffect(e:RuleNode):boolean{return e.type===LINKED_ROLE_INITIALIZE_EFFECT&&relationship(e)!==undefined&&roleKeys(e)&&e.memberSelector==='next_seat'&&exact(e,['type','relationshipKey','leaderRoleKey','memberRoleKey','memberSelector']);}
function scheduleEffect(e:RuleNode):boolean{return e.type===LINKED_ROLE_SCHEDULE_MEMBER_EFFECT&&relationship(e)!==undefined&&roleKeys(e)&&typeof e.target==='string'&&e.target.length>0&&e.baseCommandSealCost===1&&e.perActiveMemberCommandSealCost===1&&e.activateAt==='next_round_start'&&e.requireNeverMember===true&&e.requireFewerSealsBeforeSpend===true&&exact(e,['type','relationshipKey','leaderRoleKey','memberRoleKey','target','baseCommandSealCost','perActiveMemberCommandSealCost','activateAt','requireNeverMember','requireFewerSealsBeforeSpend']);}
function applyEffect(e:RuleNode):boolean{return e.type===LINKED_ROLE_APPLY_SCHEDULED_EFFECT&&relationship(e)!==undefined&&roleKeys(e)&&exact(e,['type','relationshipKey','leaderRoleKey','memberRoleKey']);}
function rulesEffect(e:RuleNode):boolean{return e.type===LINKED_ROLE_MEMBER_RULES_EFFECT&&relationship(e)!==undefined&&roleKeys(e)&&e.entryCommandSealCost===1&&e.entryOnlyBeforeClimax===true&&e.manaContributionAmount===1&&e.manaContributionMaxPerRound===1&&e.requireDifferentBattlefields===true&&exact(e,['type','relationshipKey','leaderRoleKey','memberRoleKey','entryCommandSealCost','entryOnlyBeforeClimax','manaContributionAmount','manaContributionMaxPerRound','requireDifferentBattlefields']);}
function rewardEffect(e:RuleNode):boolean{return e.type===LINKED_ROLE_BATTLE_REWARD_EFFECT&&relationship(e)!==undefined&&roleKeys(e)&&e.vpEach===1&&e.requireDifferentBattlefields===true&&exact(e,['type','relationshipKey','leaderRoleKey','memberRoleKey','vpEach','requireDifferentBattlefields']);}
function playerTarget(a:AuthoringAbility,e:RuleNode):boolean{if(a.targets.length!==1)return false;const t=a.targets[0]!;const c=rec(t.count)?t.count:{};return t.id===e.target&&t.type==='player'&&c.min===1&&c.max===1&&Array.isArray(t.constraints)&&t.constraints.length===0;}
export function isAcceptedLinkedRoleCoreAbility(a:AuthoringAbility):boolean{if(!common(a)||a.effects.length!==1)return false;const e=a.effects[0]!;
 if(initEffect(e))return a.kind==='forced_trigger'&&exact(a.activation,['trigger'])&&a.activation.trigger==='game_start'&&a.conditions.length===0&&a.targets.length===0;
 if(scheduleEffect(e))return a.kind==='phase_action'&&exact(a.activation,['phase','opens'])&&a.activation.phase==='action'&&a.activation.opens==='controller_action_window'&&a.conditions.length===0&&playerTarget(a,e);
 if(applyEffect(e))return a.kind==='forced_trigger'&&exact(a.activation,['trigger'])&&a.activation.trigger==='round_start'&&a.conditions.length===0&&a.targets.length===0;
 if(rulesEffect(e))return a.kind==='passive'&&empty(a.activation)&&a.conditions.length===0&&a.targets.length===0;
 if(rewardEffect(e))return a.kind==='forced_trigger'&&exact(a.activation,['trigger'])&&a.activation.trigger==='after_battle_ended'&&a.conditions.length===0&&a.targets.length===0;
 return false;
}
export function containsLinkedRoleCorePrivilegedNode(v:unknown):boolean{if(Array.isArray(v))return v.some(containsLinkedRoleCorePrivilegedNode);if(!rec(v))return false;if(typeof v.type==='string'&&privileged.has(v.type))return true;return Object.values(v).some(containsLinkedRoleCorePrivilegedNode);}
function runtime(s:GameState){if(!s.abilityRuntime)throw new Error('LINKED_ROLE_RUNTIME_REQUIRED');return s.abilityRuntime;}
function bag(s:GameState,p:string){const r=runtime(s);return (r.structuredPlayerFlagsByPlayer??={})[p]??={};}
function rounds(s:GameState,p:string){const r=runtime(s);return (r.structuredRoundFlagKeysByPlayer??={})[p]??={};}
function k(rel:string,field:string){return `${PREFIX}${rel}:${field}`;}
function cardDef(s:GameState,instanceId:string){const c=s.cards.find(x=>x.instanceId===instanceId);return c?runtime(s).pack.cards[c.definitionId]:undefined;}
function abilityAt(s:GameState,instanceId:string,abilityId:string){return cardDef(s,instanceId)?.abilities.find(a=>a.id===abilityId);}
function sourceValid(s:GameState,p:string,sourceCardId:string,abilityId:string):AuthoringAbility|undefined{const c=s.cards.find(x=>x.instanceId===sourceCardId);const a=abilityAt(s,sourceCardId,abilityId);if(!c||c.ownerPlayerId!==p||c.controllerPlayerId!==p||c.zone!=='skill'||!a||!isAcceptedLinkedRoleCoreAbility(a))return undefined;return a;}
function providers(s:GameState,leaderId:string,rel:string,type:string){const out:Array<{sourceCardId:string;ability:AuthoringAbility}>=[];for(const c of s.cards){if(c.ownerPlayerId!==leaderId||c.controllerPlayerId!==leaderId||c.zone!=='skill')continue;const d=runtime(s).pack.cards[c.definitionId];if(!d)continue;for(const a of d.abilities){if(!isAcceptedLinkedRoleCoreAbility(a))continue;const e=a.effects[0]!;if(e.type===type&&relationship(e)===rel)out.push({sourceCardId:c.instanceId,ability:a});}}return out;}
function uniqueProvider(s:GameState,leaderId:string,rel:string,type:string){const x=providers(s,leaderId,rel,type);return x.length===1?x[0]:undefined;}
function leaderActive(s:GameState,leaderId:string,rel:string,e:RuleNode):boolean{const b=bag(s,leaderId);return b[k(rel,'leader')]===true&&b[k(rel,'leaderRole')]===(e.leaderRoleKey as string);}
function memberLeader(s:GameState,memberId:string,rel:string,e:RuleNode):string|undefined{const b=bag(s,memberId);return b[k(rel,'memberRole')]===(e.memberRoleKey as string)&&typeof b[k(rel,'memberLeader')]==='string'?String(b[k(rel,'memberLeader')]):undefined;}
function isBattlefield(s:GameState,loc:string|undefined){if(!loc)return false;const l=s.map.locations.find(x=>x.id===loc);return !!l&&(l.tags.includes('battlefield')||l.rewardHooks.includes('battle_rewards'));}
function seals(s:GameState,p:string){const pl=s.players.find(x=>x.id===p) as (GameState['players'][number]&{commandSpells?:number})|undefined;const n=Number(pl?.commandSpells??3);return Number.isSafeInteger(n)&&n>=0?n:0;}
function setSeals(s:GameState,p:string,n:number,sourceCardId:string,abilityId:string){const pl=s.players.find(x=>x.id===p) as (GameState['players'][number]&{commandSpells?:number})|undefined;if(!pl)throw new Error('LINKED_ROLE_PLAYER_MISSING');const before=seals(s,p);pl.commandSpells=n;runtime(s).events.push({type:'command_seals_adjusted',playerId:p,sourceCardId,abilityId,resource:'command_seals',delta:n-before,before,after:n});}
function activeMembers(s:GameState,leaderId:string,rel:string,e:RuleNode){return s.players.filter(p=>p.status==='active'&&memberLeader(s,p.id,rel,e)===leaderId);}
export function linkedRoleEligibleScheduleTargetIds(s:GameState,ctx:EffectContext,a:AuthoringAbility):string[]{if(!isAcceptedLinkedRoleCoreAbility(a)||a.effects[0]?.type!==LINKED_ROLE_SCHEDULE_MEMBER_EFFECT)return[];const e=a.effects[0]!,rel=relationship(e)!;if(!sourceValid(s,ctx.controllerId,ctx.sourceCardId,ctx.abilityId)||!leaderActive(s,ctx.controllerId,rel,e))return[];const leaderSeals=seals(s,ctx.controllerId);return s.players.filter(p=>p.status==='active'&&p.id!==ctx.controllerId&&bag(s,p.id)[k(rel,'ever')]!==true&&seals(s,p.id)<leaderSeals).map(p=>p.id);}
export function linkedRoleActiveMemberIds(s:GameState,leaderId:string,relationshipKey:string):string[]{const provider=uniqueProvider(s,leaderId,relationshipKey,LINKED_ROLE_MEMBER_RULES_EFFECT);if(!provider)return[];const e=provider.ability.effects[0]!;if(!leaderActive(s,leaderId,relationshipKey,e))return[];return activeMembers(s,leaderId,relationshipKey,e).map(p=>p.id);}
export function linkedRoleEntrySealAuthority(s:GameState,entrantId:string,targetLocationId:string):{cost:number;leaderId:string;sourceCardId:string;abilityId:string}|undefined{if(!s.abilityRuntime||!isBattlefield(s,targetLocationId))return undefined;const entrant=s.players.find(p=>p.id===entrantId&&p.status==='active');if(!entrant)return undefined;const found:Array<{cost:number;leaderId:string;sourceCardId:string;abilityId:string}>=[];for(const leader of s.players.filter(p=>p.status==='active'&&p.id!==entrantId)){for(const c of s.cards.filter(c=>c.ownerPlayerId===leader.id&&c.controllerPlayerId===leader.id&&c.zone==='skill')){const d=runtime(s).pack.cards[c.definitionId];if(!d)continue;for(const a of d.abilities){if(!isAcceptedLinkedRoleCoreAbility(a)||a.effects[0]?.type!==LINKED_ROLE_MEMBER_RULES_EFFECT)continue;const e=a.effects[0]!,rel=relationship(e)!;if(!leaderActive(s,leader.id,rel,e)||memberLeader(s,entrantId,rel,e)!==leader.id||leader.locationId!==targetLocationId||entrant.locationId===targetLocationId)continue;const climax=(s as unknown as {modeState?:{currentSituationIsClimax?:boolean}}).modeState?.currentSituationIsClimax===true||s.round.roundNumber>=9;if(e.entryOnlyBeforeClimax===true&&climax)continue;found.push({cost:Number(e.entryCommandSealCost),leaderId:leader.id,sourceCardId:c.instanceId,abilityId:a.id});}}}if(found.length>1)throw new Error('LINKED_ROLE_ENTRY_CONFLICT');return found[0];}
export function applyLinkedRoleEntrySealCost(s:GameState,entrantId:string,targetLocationId:string):number{const auth=linkedRoleEntrySealAuthority(s,entrantId,targetLocationId);if(!auth)return 0;const before=seals(s,entrantId);if(before<auth.cost)throw new Error('LINKED_ROLE_ENTRY_SEALS_INSUFFICIENT');setSeals(s,entrantId,before-auth.cost,auth.sourceCardId,auth.abilityId);return auth.cost;}
export function linkedRoleMaximumContributionAmount(s:GameState,beneficiaryId:string):number{ return s.players.some((candidate)=>candidate.id!==beneficiaryId&&linkedRoleCanContribute(s,beneficiaryId,candidate.id))?1:0; }
export function linkedRoleCanContribute(s:GameState,beneficiaryId:string,contributorId:string):boolean{if(!s.abilityRuntime||beneficiaryId===contributorId)return false;const beneficiary=s.players.find(p=>p.id===beneficiaryId&&p.status==='active');const contributor=s.players.find(p=>p.id===contributorId&&p.status==='active');if(!beneficiary||!contributor||!isBattlefield(s,beneficiary.locationId)||!isBattlefield(s,contributor.locationId)||beneficiary.locationId===contributor.locationId||contributor.mana<1)return false;for(const c of s.cards.filter(c=>c.ownerPlayerId===contributorId&&c.controllerPlayerId===contributorId&&c.zone==='skill')){const d=runtime(s).pack.cards[c.definitionId];if(!d)continue;for(const a of d.abilities){if(!isAcceptedLinkedRoleCoreAbility(a)||a.effects[0]?.type!==LINKED_ROLE_MEMBER_RULES_EFFECT)continue;const e=a.effects[0]!,rel=relationship(e)!;if(!leaderActive(s,contributorId,rel,e)||memberLeader(s,beneficiaryId,rel,e)!==contributorId)continue;if(rounds(s,beneficiaryId)[k(rel,'manaContribution')]===s.round.roundNumber)continue;return true;}}return false;}
export interface LinkedRoleContributionPart{contributorPlayerId:string;amount:1;relationshipKey:string;sourceCardId:string;abilityId:string;}
export function resolveLinkedRoleContributionChoices(s:GameState,beneficiaryId:string,choices:readonly ManaContributionChoice[]):LinkedRoleContributionPart[]{if(choices.length>1)throw new Error('LINKED_ROLE_CONTRIBUTION_TOO_MANY');const out:LinkedRoleContributionPart[]=[];const seen=new Set<string>();for(const choice of choices){if(seen.has(choice.contributorPlayerId))throw new Error('LINKED_ROLE_CONTRIBUTION_DUPLICATE');seen.add(choice.contributorPlayerId);if(choice.amount!==1||!linkedRoleCanContribute(s,beneficiaryId,choice.contributorPlayerId))continue;const matches:Array<LinkedRoleContributionPart>=[];for(const c of s.cards.filter(c=>c.ownerPlayerId===choice.contributorPlayerId&&c.controllerPlayerId===choice.contributorPlayerId&&c.zone==='skill')){const d=runtime(s).pack.cards[c.definitionId];if(!d)continue;for(const a of d.abilities){if(!isAcceptedLinkedRoleCoreAbility(a)||a.effects[0]?.type!==LINKED_ROLE_MEMBER_RULES_EFFECT)continue;const e=a.effects[0]!,rel=relationship(e)!;if(memberLeader(s,beneficiaryId,rel,e)===choice.contributorPlayerId&&leaderActive(s,choice.contributorPlayerId,rel,e)&&rounds(s,beneficiaryId)[k(rel,'manaContribution')]!==s.round.roundNumber)matches.push({contributorPlayerId:choice.contributorPlayerId,amount:1,relationshipKey:rel,sourceCardId:c.instanceId,abilityId:a.id});}}if(matches.length!==1)throw new Error('LINKED_ROLE_CONTRIBUTION_CONFLICT');out.push(matches[0]!);}return out;}
export function commitLinkedRoleContributions(s:GameState,beneficiaryId:string,parts:readonly LinkedRoleContributionPart[]):void{for(const part of parts){const contributor=s.players.find(p=>p.id===part.contributorPlayerId);if(!contributor||contributor.mana<1)throw new Error('LINKED_ROLE_CONTRIBUTOR_STATE_CHANGED');}for(const part of parts){const contributor=s.players.find(p=>p.id===part.contributorPlayerId)!;contributor.mana-=1;rounds(s,beneficiaryId)[k(part.relationshipKey,'manaContribution')]=s.round.roundNumber;runtime(s).events.push({type:'linked_role_mana_contributed',playerId:beneficiaryId,controllerId:part.contributorPlayerId,sourceCardId:part.sourceCardId,abilityId:part.abilityId,resource:'mana',delta:-1,before:contributor.mana+1,after:contributor.mana});}}
function nextSeatPlayer(s:GameState,leaderId:string){const active=s.players.filter(p=>p.status==='active').slice().sort((a,b)=>a.seat-b.seat);const i=active.findIndex(p=>p.id===leaderId);return i<0||active.length<2?undefined:active[(i+1)%active.length];}
function markMember(s:GameState,leaderId:string,memberId:string,rel:string,e:RuleNode){const b=bag(s,memberId);b[k(rel,'memberLeader')]=leaderId;b[k(rel,'lastLeader')]=leaderId;b[k(rel,'memberRole')]=String(e.memberRoleKey);b[k(rel,'ever')]=true;}
function clearMember(s:GameState,memberId:string,rel:string){const b=bag(s,memberId);delete b[k(rel,'memberLeader')];delete b[k(rel,'memberRole')];}
export function removeLinkedRoleMember(s:GameState,leaderId:string,memberId:string,relationshipKey:string):boolean{const b=bag(s,memberId);if(b[k(relationshipKey,'memberLeader')]!==leaderId)return false;const provider=uniqueProvider(s,leaderId,relationshipKey,LINKED_ROLE_MEMBER_RULES_EFFECT);if(!provider)return false;clearMember(s,memberId,relationshipKey);return true;}
function winLocations(event:AbilityEvent):Array<{battlefieldId:string;winnerPlayerIds:string[]}>{return Array.isArray(event.battleOutcomes)?event.battleOutcomes.filter(x=>x&&typeof x.battlefieldId==='string'&&Array.isArray(x.winnerPlayerIds)).map(x=>({battlefieldId:x.battlefieldId,winnerPlayerIds:[...new Set(x.winnerPlayerIds.filter(id=>typeof id==='string'))]})):[];}
export function canExecuteLinkedRoleCoreEffect(s:GameState,ctx:EffectContext,a:AuthoringAbility):boolean{if(!isAcceptedLinkedRoleCoreAbility(a)||!sourceValid(s,ctx.controllerId,ctx.sourceCardId,ctx.abilityId))return false;const e=a.effects[0]!,rel=relationship(e)!;if(e.type===LINKED_ROLE_INITIALIZE_EFFECT)return ctx.event?.type==='game_start';if(e.type===LINKED_ROLE_SCHEDULE_MEMBER_EFFECT){const cost=1+activeMembers(s,ctx.controllerId,rel,e).length;return leaderActive(s,ctx.controllerId,rel,e)&&seals(s,ctx.controllerId)>=cost&&linkedRoleEligibleScheduleTargetIds(s,ctx,a).length>0;}if(e.type===LINKED_ROLE_APPLY_SCHEDULED_EFFECT)return ctx.event?.type==='round_start'&&leaderActive(s,ctx.controllerId,rel,e);if(e.type===LINKED_ROLE_MEMBER_RULES_EFFECT)return leaderActive(s,ctx.controllerId,rel,e);if(e.type===LINKED_ROLE_BATTLE_REWARD_EFFECT)return ctx.event?.type==='after_battle_ended'&&leaderActive(s,ctx.controllerId,rel,e)&&winLocations(ctx.event).length>0;return false;}
export function resolveLinkedRoleCoreEffect(s:GameState,ctx:EffectContext,a:AuthoringAbility):boolean{if(!canExecuteLinkedRoleCoreEffect(s,ctx,a))return false;const e=a.effects[0]!,rel=relationship(e)!;if(e.type===LINKED_ROLE_INITIALIZE_EFFECT){const lb=bag(s,ctx.controllerId);lb[k(rel,'leader')]=true;lb[k(rel,'leaderRole')]=String(e.leaderRoleKey);const member=nextSeatPlayer(s,ctx.controllerId);if(member)markMember(s,ctx.controllerId,member.id,rel,e);return true;}if(e.type===LINKED_ROLE_SCHEDULE_MEMBER_EFFECT){const target=ctx.selections[String(e.target)]?.[0];if(!target||!linkedRoleEligibleScheduleTargetIds(s,ctx,a).includes(target))return false;const cost=1+activeMembers(s,ctx.controllerId,rel,e).length;const before=seals(s,ctx.controllerId);if(before<cost)return false;setSeals(s,ctx.controllerId,before-cost,ctx.sourceCardId,ctx.abilityId);const b=bag(s,target);b[k(rel,'pendingLeader')]=ctx.controllerId;b[k(rel,'pendingRound')]=s.round.roundNumber+1;b[k(rel,'pendingMemberRole')]=String(e.memberRoleKey);return true;}if(e.type===LINKED_ROLE_APPLY_SCHEDULED_EFFECT){for(const p of s.players){const b=bag(s,p.id);if(b[k(rel,'pendingLeader')]===ctx.controllerId&&b[k(rel,'pendingRound')]===s.round.roundNumber&&b[k(rel,'pendingMemberRole')]===e.memberRoleKey){markMember(s,ctx.controllerId,p.id,rel,e);delete b[k(rel,'pendingLeader')];delete b[k(rel,'pendingRound')];delete b[k(rel,'pendingMemberRole')];}}return true;}if(e.type===LINKED_ROLE_MEMBER_RULES_EFFECT)return true;if(e.type===LINKED_ROLE_BATTLE_REWARD_EFFECT){const outcomes=winLocations(ctx.event!);const leaderBag=bag(s,ctx.controllerId);for(const o of outcomes){if(o.winnerPlayerIds.includes(ctx.controllerId)){leaderBag[k(rel,'winRound')]=s.round.roundNumber;leaderBag[k(rel,'winLocation')]=o.battlefieldId;}for(const m of activeMembers(s,ctx.controllerId,rel,e)){if(o.winnerPlayerIds.includes(m.id)){const mb=bag(s,m.id);mb[k(rel,'winRound')]=s.round.roundNumber;mb[k(rel,'winLocation')]=o.battlefieldId;}}}if(leaderBag[k(rel,'winRound')]===s.round.roundNumber&&typeof leaderBag[k(rel,'winLocation')]==='string'){for(const m of activeMembers(s,ctx.controllerId,rel,e)){const mb=bag(s,m.id);if(mb[k(rel,'winRound')]!==s.round.roundNumber||typeof mb[k(rel,'winLocation')]!=='string'||mb[k(rel,'winLocation')]===leaderBag[k(rel,'winLocation')]||mb[k(rel,'rewardRound')]===s.round.roundNumber)continue;const leader=s.players.find(p=>p.id===ctx.controllerId)!;leader.vp+=bloodlustVpGainAdjustment(s,leader.id,1);m.vp+=bloodlustVpGainAdjustment(s,m.id,1);mb[k(rel,'rewardRound')]=s.round.roundNumber;}}return true;}return false;}
export function isLinkedRoleCoreRuntimeProvenanceValidForRestore(s:GameState):boolean{try{
 const r=s.abilityRuntime;if(!r)return true;const bags=r.structuredPlayerFlagsByPlayer??{};const roundBags=r.structuredRoundFlagKeysByPlayer??{};const playerIds=new Set<string>(s.players.map(p=>p.id));const locationIds=new Set<string>(s.map.locations.map(l=>l.id));
 const relationshipLeaders=new Map<string,string>();
 for(const p of s.players){const b=bags[p.id]??{};for(const raw of Object.keys(b).filter(x=>x.startsWith(PREFIX))){const rest=raw.slice(PREFIX.length),cut=rest.lastIndexOf(':');if(cut<=0)return false;const rel=rest.slice(0,cut),field=rest.slice(cut+1),value=b[raw];if(!key(rel))return false;const known=['leader','leaderRole','memberLeader','lastLeader','memberRole','ever','pendingLeader','pendingRound','pendingMemberRole','winRound','winLocation','rewardRound'];if(!known.includes(field))return false;if(['leader','ever'].includes(field)&&value!==true)return false;if(['pendingRound','winRound','rewardRound'].includes(field)&&(!Number.isSafeInteger(value)||Number(value)<1||Number(value)>s.round.roundNumber+1))return false;if(['leaderRole','memberLeader','lastLeader','memberRole','pendingLeader','pendingMemberRole','winLocation'].includes(field)&&typeof value!=='string')return false;if(field==='winLocation'&&!locationIds.has(String(value)))return false;}
   for(const [relValue,flag] of Object.entries(b).filter(([raw])=>raw.startsWith(PREFIX)&&raw.endsWith(':leader'))){if(flag!==true)continue;const rel=relValue.slice(PREFIX.length,-':leader'.length);const init=providers(s,p.id,rel,LINKED_ROLE_INITIALIZE_EFFECT);const rules=providers(s,p.id,rel,LINKED_ROLE_MEMBER_RULES_EFFECT);if(init.length!==1||rules.length!==1)return false;const initEffect=init[0]!.ability.effects[0]!,rulesEffect=rules[0]!.ability.effects[0]!;if(b[k(rel,'leaderRole')]!==initEffect.leaderRoleKey||rulesEffect.leaderRoleKey!==initEffect.leaderRoleKey||rulesEffect.memberRoleKey!==initEffect.memberRoleKey)return false;if(relationshipLeaders.has(rel)&&relationshipLeaders.get(rel)!==p.id)return false;relationshipLeaders.set(rel,p.id);}
 }
 for(const p of s.players){const b=bags[p.id]??{};const rels=new Set(Object.keys(b).filter(x=>x.startsWith(PREFIX)).map(raw=>{const rest=raw.slice(PREFIX.length);return rest.slice(0,rest.lastIndexOf(':'));}));for(const rel of rels){const leaderId=typeof b[k(rel,'memberLeader')]==='string'?String(b[k(rel,'memberLeader')]):undefined;const lastLeader=typeof b[k(rel,'lastLeader')]==='string'?String(b[k(rel,'lastLeader')]):undefined;const pendingLeader=typeof b[k(rel,'pendingLeader')]==='string'?String(b[k(rel,'pendingLeader')]):undefined;const authorityLeader=leaderId??lastLeader??pendingLeader??relationshipLeaders.get(rel);if((b[k(rel,'ever')]===true||leaderId||pendingLeader)&&(!authorityLeader||!playerIds.has(authorityLeader)))return false;if(authorityLeader){const rules=providers(s,authorityLeader,rel,LINKED_ROLE_MEMBER_RULES_EFFECT);if(rules.length!==1)return false;const e=rules[0]!.ability.effects[0]!;if(leaderId&&b[k(rel,'memberRole')]!==e.memberRoleKey)return false;if(pendingLeader&&b[k(rel,'pendingMemberRole')]!==e.memberRoleKey)return false;if(lastLeader&&lastLeader!==authorityLeader&&leaderId!==undefined)return false;}}
   const rb=roundBags[p.id]??{};for(const [raw,value] of Object.entries(rb).filter(([x])=>x.startsWith(PREFIX))){const rest=raw.slice(PREFIX.length),cut=rest.lastIndexOf(':');if(cut<=0||rest.slice(cut+1)!=='manaContribution'||!key(rest.slice(0,cut))||!Number.isSafeInteger(value)||Number(value)<1||Number(value)>s.round.roundNumber)return false;const rel=rest.slice(0,cut);const last=typeof b[k(rel,'lastLeader')]==='string'?String(b[k(rel,'lastLeader')]):undefined;if(!last||providers(s,last,rel,LINKED_ROLE_MEMBER_RULES_EFFECT).length!==1)return false;}
 }
 return true;}catch{return false;}}
