import type { GameState } from '../schema/game';
import type { AuthoringAbility, EffectContext, RuleNode } from './types';

export const RECYCLE_ACTIVE_BASIC_FOR_PRINTED_COST_MANA_EFFECT = 'recycle_active_basic_for_printed_cost_mana' as const;

function rec(v: unknown): v is Record<string, unknown> { return !!v && typeof v === 'object' && !Array.isArray(v); }
function exact(v: unknown, keys: readonly string[]): boolean { if(!rec(v)) return false; const a=Object.keys(v); return a.length===keys.length&&a.every((k)=>keys.includes(k)); }
function standard(a: AuthoringAbility): boolean { return a.cost.length===0&&a.creates.length===0&&a.ruleModifiers.length===0&&Object.keys(a.lifecycle).length===0&&Object.keys(a.limit).length===0&&Object.keys(a.visibility).length===0&&exact(a.responseWindow,['order','passBehavior'])&&a.responseWindow.order==='turn_order'&&a.responseWindow.passBehavior==='decline_this_window'&&a.execution.mode==='automatic'&&Array.isArray(a.execution.allowedOperations)&&a.execution.allowedOperations.length===0; }
function exactTarget(a: AuthoringAbility): boolean { if(a.targets.length!==1)return false; const t=a.targets[0]!; const scope=rec(t.scope)?t.scope:{}; const count=rec(t.count)?t.count:{}; return t.id==='active_basic_attack'&&t.type==='card_instance'&&exact(scope,['zone','owner','controller'])&&scope.zone==='attack_area'&&scope.owner==='controller'&&scope.controller==='self'&&exact(count,['min','max'])&&count.min===1&&count.max===1&&Array.isArray(t.constraints)&&t.constraints.length===0; }
function exactEffect(e: RuleNode): boolean { return e.type===RECYCLE_ACTIVE_BASIC_FOR_PRINTED_COST_MANA_EFFECT&&e.target==='active_basic_attack'&&e.printedCostMultiplier===2&&exact(e,['type','target','printedCostMultiplier']); }
export function isAcceptedOriginStillnessPrintedCostAbility(a: AuthoringAbility): boolean { return standard(a)&&a.kind==='forced_trigger'&&exact(a.activation,['trigger'])&&a.activation.trigger==='after_battle_ended'&&a.conditions.length===0&&exactTarget(a)&&a.effects.length===1&&exactEffect(a.effects[0]!); }
export function containsOriginStillnessPrintedCostPrivilegedNode(v: unknown): boolean { if(Array.isArray(v))return v.some(containsOriginStillnessPrintedCostPrivilegedNode); if(!rec(v))return false; if(v.type===RECYCLE_ACTIVE_BASIC_FOR_PRINTED_COST_MANA_EFFECT)return true; return Object.values(v).some(containsOriginStillnessPrintedCostPrivilegedNode); }
function runtime(s: GameState){if(!s.abilityRuntime)throw new Error('ORIGIN_STILLNESS_RUNTIME_REQUIRED');return s.abilityRuntime;}
function providerValid(s:GameState,ctx:EffectContext,a:AuthoringAbility):boolean{const source=s.cards.find((c)=>c.instanceId===ctx.sourceCardId);return isAcceptedOriginStillnessPrintedCostAbility(a)&&!!source&&source.ownerPlayerId===ctx.controllerId&&source.controllerPlayerId===ctx.controllerId&&source.zone==='skill';}
export function originStillnessEligibleActiveBasicIds(s:GameState,ctx:EffectContext,a:AuthoringAbility):string[]{if(!providerValid(s,ctx,a)||ctx.event?.type!=='after_battle_ended'||typeof ctx.event.battlePhaseResolutionId!=='string')return[];return s.cards.filter((c)=>{const d=runtime(s).pack.cards[c.definitionId];const st=runtime(s).cardState[c.instanceId];return c.ownerPlayerId===ctx.controllerId&&c.controllerPlayerId===ctx.controllerId&&c.zone==='attack_area'&&d?.cardType==='basic_attack'&&st?.active===true&&st.faceDown!==true;}).map((c)=>c.instanceId);}
export function originStillnessPrintedManaGain(s:GameState,ctx:EffectContext,a:AuthoringAbility,selectedId:string):number|undefined{if(!originStillnessEligibleActiveBasicIds(s,ctx,a).includes(selectedId))return undefined;const card=s.cards.find((c)=>c.instanceId===selectedId);const d=card?runtime(s).pack.cards[card.definitionId]:undefined;const cost=Number(d?.cardFace.cost??0);return Number.isFinite(cost)&&cost>=0?cost*2:undefined;}
